/**
 * Fallback CSS-path walker — the safety net for the v1 element-selector
 * algorithm.
 *
 * When the orchestrator's strategy chain finds nothing usable across the full
 * ancestor walk, the engine invokes this fallback. It produces a positional
 * selector by walking up from the target to <html>, expressing each step as
 * either an id anchor (when one survives the autogen filter) or a
 * `tag:nth-of-type(n)` step.
 *
 * Key differences from the legacy autocapture `cssPath`:
 *
 *   1. Ids are filtered through `getStableId`, which honors the
 *      explicit-tracking-attribute suppression signal AND the autogenerated-id
 *      pattern pack. The legacy `cssPath` would happily anchor on `id=":r5:"`
 *      and produce selectors that never match across page loads.
 *
 *   2. Classes — when they're used at all for sibling disambiguation — are
 *      filtered through `filterClasses` against the unstable-class pattern
 *      pack. The current v1 implementation here doesn't emit classes (we lean
 *      entirely on `:nth-of-type` for sibling disambiguation), but the
 *      filtering helper is wired through so future iterations can opt back in
 *      surgically without re-deriving the policy.
 *
 *   3. A unique anchor id terminates the walk early — once we hit `body#main`,
 *      we don't need to keep walking up to `<html>`.
 *
 *   4. Ambiguous id anchors are skipped. Duplicate ids are invalid HTML but
 *      common enough in the wild that fallback must not emit selectors that
 *      resolve to the wrong target.
 *
 * Output format mirrors the orchestrator's output: `<anchor> > <descent>`.
 * When no usable id is found anywhere on the walk, the fallback emits a
 * pure-positional selector rooted at `html`.
 *
 * See the design doc:
 *   packages/plugin-autocapture-browser/element-selector-strategy-v1-no-classes.md
 */

import { ResolvedSelectorConfig } from './types';
import { getStableId } from './helpers/get-stable-id';
import { escapeIdForCss } from './helpers/escape-id';
import { positionalStep, SHADOW_CHILD_CHAIN_PREFIX } from './helpers/shadow';

export interface FallbackCssPathOptions {
  /** Document or shadow root used for uniqueness checks. Defaults to the target's owner document. */
  scope?: ParentNode;
}

/**
 * Build a positional CSS selector for `el`, using stable ids as anchors when
 * available and falling back to `tag:nth-of-type(n)` for disambiguation.
 *
 * Honors `config.maxAncestorWalkDepth` defensively — once the depth limit is
 * reached, the walker stops and returns whatever it has built so far rooted at
 * the deepest reached ancestor.
 */
export function fallbackCssPath(
  el: Element,
  config: ResolvedSelectorConfig,
  options: FallbackCssPathOptions = {},
): string {
  const scope: ParentNode = options.scope ?? el.ownerDocument ?? document;
  const scopeIsShadowRoot = isShadowRootScope(scope);
  const segments: string[] = [];
  let cursor: Element | null = el;
  let depth = 0;

  while (cursor !== null) {
    if (config.maxAncestorWalkDepth !== undefined && depth > config.maxAncestorWalkDepth) {
      break;
    }

    const id = getStableId(cursor, config);
    if (id !== null) {
      // Anchor format mirrors the stableId strategy: `tag#id` with the id
      // CSS-escaped. Only terminate if the composed selector uniquely resolves
      // to the target; duplicate ids should fall through to positional steps.
      const anchorSegment = `${cursor.tagName.toLowerCase()}#${escapeIdForCss(id)}`;
      const candidate = [anchorSegment, ...segments].join(' > ');
      if (isUniqueMatch(scope, candidate, el)) {
        return candidate;
      }
    }

    // `positionalStep` mirrors the prior `tag:nth-of-type(n)` step for elements
    // with a parent and bare `tag` for the document root, and additionally
    // disambiguates a shadow-root-top element against its `ShadowRoot` siblings
    // (its `parentElement` is null but it can have same-tag peers).
    segments.unshift(positionalStep(cursor));
    cursor = cursor.parentElement;
    depth += 1;
  }

  const path = segments.join(' > ');

  // In the light DOM the chain's first segment is `<html>` (unique), which
  // anchors it. Inside a shadow root there is no anchoring root element, so a
  // bare positional chain would match tree-wide. When we reached the top of the
  // tree naturally (`cursor === null`, not a depth-limit break), the chain spans
  // root → target via direct children — mark it so `resolveSelector` resolves it
  // by direct-child descent. The marker is explicit (not inferred from the step
  // syntax), so it stays correct even if steps later include classes.
  if (scopeIsShadowRoot && cursor === null) {
    return `${SHADOW_CHILD_CHAIN_PREFIX}${path}`;
  }

  return path;
}

/** True when `scope` is a shadow root (tolerates environments without the global). */
function isShadowRootScope(scope: ParentNode): boolean {
  return typeof ShadowRoot !== 'undefined' && scope instanceof ShadowRoot;
}

function isUniqueMatch(scope: ParentNode, selector: string, el: Element): boolean {
  let matches: NodeListOf<Element>;
  try {
    matches = scope.querySelectorAll(selector);
  } catch (_e) {
    return false;
  }
  return matches.length === 1 && matches[0] === el;
}
