/**
 * @amplitude/element-selector
 *
 * Shared element-selector algorithm consumed by autocapture, the
 * app.amplitude.com tagging UI, and the Chrome extension visual tagger.
 *
 * This file is the package's public API surface. Subsequent PRs land the
 * orchestrator, fallback, config resolver, and factory; the strategies +
 * primitives below are the foundation everything composes on top of.
 *
 * See the design doc:
 *   packages/plugin-autocapture-browser/element-selector-strategy-v1-no-classes.md
 */

export const PACKAGE_NAME = '@amplitude/element-selector';

// ===== Types =====
export type {
  Strategy,
  StrategyContext,
  ResolvedSelectorConfig,
  ElementSelectorRemoteConfig,
  SelectorEngine,
} from './types';

// ===== Pattern packs =====
export {
  DEFAULT_AUTOGENERATED_ID_PATTERNS,
  compile as compileAutogeneratedIdPatterns,
  isStableId,
} from './patterns/autogenerated-ids';

export {
  DEFAULT_UNSTABLE_CLASS_PATTERNS,
  compile as compileUnstableClassPatterns,
  filterClasses,
} from './patterns/unstable-classes';

// ===== Helpers =====
export { getStableId } from './helpers/get-stable-id';
export { describeRelative } from './helpers/describe-relative';

// ===== Strategies =====
export { explicitTrackingAttribute } from './strategies/explicit-tracking-attribute';
export { stableId as stableIdStrategy } from './strategies/stable-id';
