/**
 * @amplitude/element-selector
 *
 * Shared element-selector algorithm consumed by autocapture, the
 * app.amplitude.com tagging UI, and the Chrome extension visual tagger.
 *
 * This file is the package's public API surface. The orchestrator, fallback,
 * config resolver, and engine factory compose on top of the primitives
 * (types, pattern packs, helpers, strategies) to produce the runtime engine
 * consumers actually call.
 *
 * See the design doc:
 *   packages/plugin-autocapture-browser/element-selector-strategy-v1-no-classes.md
 */

export const PACKAGE_NAME = '@amplitude/element-selector';

// ===== Types =====
export type {
  Strategy,
  StrategyContext,
  ResolvedSelectorConfig,
  ElementSelectorRemoteConfig,
  SelectorEngine,
} from './types';

// ===== Pattern packs =====
export {
  DEFAULT_AUTOGENERATED_ID_PATTERNS,
  compile as compileAutogeneratedIdPatterns,
  isStableId,
} from './patterns/autogenerated-ids';

export {
  DEFAULT_UNSTABLE_CLASS_PATTERNS,
  compile as compileUnstableClassPatterns,
  filterClasses,
} from './patterns/unstable-classes';

// ===== Helpers =====
export { getStableId } from './helpers/get-stable-id';
export { describeRelative } from './helpers/describe-relative';

// ===== Strategies =====
export { explicitTrackingAttribute } from './strategies/explicit-tracking-attribute';
export { stableId as stableIdStrategy } from './strategies/stable-id';

// ===== Orchestrator + fallback =====
// Exposed publicly so the dashboard / Chrome extension can call them ad-hoc
// without instantiating a full engine — useful for preview / debugging flows.
export { runOrchestrator, DEFAULT_STRATEGIES } from './orchestrator';
export type { OrchestratorOptions } from './orchestrator';
export { fallbackCssPath } from './fallback-css-path';

// ===== Config resolver =====
export { resolveSelectorConfig, DEFAULT_RESOLVED_CONFIG } from './config/resolve-config';

// ===== Engine factory =====
export { createSelectorEngine } from './engine';
export type { CreateSelectorEngineOptions } from './engine';
