const baseConfig = require('../../jest.config.js');
const package = require('./package');

module.exports = {
  ...baseConfig,
  displayName: package.name,
  rootDir: '.',
  testEnvironment: 'jsdom',
  // version.ts is auto-generated by the `version-file` lifecycle and not consumed by targeting
  // (no VERSION import, unlike the SDK packages), so exclude it from coverage.
  coveragePathIgnorePatterns: ['index.ts', 'version.ts'],
  setupFilesAfterEnv: ['./test/jest-setup.js'],
};
