const baseConfig = require('../../jest.config.js');
const package = require('./package');

module.exports = {
  ...baseConfig,
  displayName: package.name,
  rootDir: '.',
  testEnvironment: 'jsdom',
  // version.ts is auto-generated by the `version-file` lifecycle (run by lerna on version bump) and
  // isn't consumed by targeting (no VERSION import), so it can't be covered — exclude it. Without
  // this, publishing targeting (now that it's no longer private) fails its 100% coverage threshold.
  coveragePathIgnorePatterns: ['index.ts', 'version.ts'],
  setupFilesAfterEnv: ['./test/jest-setup.js'],
};
