packages:
  - packages/*
  - apps/*

blockExoticSubdeps: true

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - '@amplitude/*'

# These are dependencies that run the postinstall script
# Only add dependencies to this if they have been vetted for security
onlyBuiltDependencies:
  - core-js
  - esbuild
  - msw
  - nx
  - unrs-resolver

trustPolicy: true
