packages:
  - packages/*
  - apps/*

blockExoticSubdeps: true

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - '@amplitude/*'

onlyBuiltDependencies:
  - core-js
  - esbuild
  - msw
  - nx
  - unrs-resolver

trustPolicy: true
