/**
 * Stable config hashing for the element-selector algorithm.
 *
 * Goal: produce a deterministic fingerprint of the *resolved* selector config
 * so analytics events (Page Viewed, Element Clicked, Rage Click, Viewport
 * Content Updated) can record which algorithm configuration was active when
 * they fired. The dashboard and Chrome-extension visual tagger compute the same
 * hash from the same config, so a single value identifies the config across all
 * three surfaces.
 *
 * The pipeline matches the agreed approach:
 *
 *   1. Project `ResolvedSelectorConfig` into a fully-specified, JSON-safe
 *      snapshot (`SelectorConfigSnapshot`).
 *   2. Canonicalize the snapshot with RFC 8785 (JCS) via the `canonicalize`
 *      package — deterministic key ordering, normalized number representation,
 *      and no insignificant whitespace.
 *   3. SHA-256 the canonical string and return lowercase hex.
 *
 * Canonicalization decisions (each maps to a requirement):
 *
 *   - **Sort object keys recursively** — handled by `canonicalize` (RFC 8785).
 *   - **Normalize numbers** — handled by `canonicalize`; the only numeric field
 *     (`maxAncestorWalkDepth`) is already a floored integer or `undefined`.
 *   - **Normalize whitespace** — `canonicalize` emits no insignificant
 *     whitespace.
 *   - **Unicode normalization (NFC)** — every string we feed in (the tracking
 *     attribute name and each pattern's source) is `String.prototype.normalize`'d
 *     to NFC so visually-identical strings with different code-point sequences
 *     hash identically.
 *   - **Defaults: omitted vs. explicit** — we always hash the *resolved* config
 *     (defaults already applied by `resolveSelectorConfig`). Every field is
 *     therefore always present, so "field omitted from remote config" and
 *     "field explicitly set to its default" canonicalize to the same snapshot
 *     and produce the same hash.
 *
 * RegExp handling: `RegExp.prototype.source` drops flags, and the default
 * autogenerated-id pack ships a case-insensitive pattern (`/^[a-f0-9]{16,}$/i`).
 * We therefore serialize each pattern via `RegExp.prototype.toString()`
 * (`/source/flags`) so flags are part of the fingerprint and two patterns that
 * differ only by flags hash differently. Array order is preserved as authored
 * — `canonicalize` keeps array order per RFC 8785, and the order in which a
 * customer lists patterns is part of their configuration.
 */

import canonicalize from 'canonicalize';
import { ResolvedSelectorConfig } from '../types';
import { sha256Hex } from '../helpers/sha256';

/**
 * Fully-specified, JSON-serializable projection of `ResolvedSelectorConfig`.
 * This is the exact shape that gets canonicalized and hashed; it is exported so
 * tests and downstream tooling can introspect precisely what the hash covers.
 */
export interface SelectorConfigSnapshot {
  enabled: boolean;
  explicitTrackingAttribute: string;
  autogeneratedIdPatterns: string[];
  unstableClassPatterns: string[];
  /** `undefined` (no limit) is normalized to `null` so it always serializes. */
  maxAncestorWalkDepth: number | null;
}

/** NFC-normalize a string so equivalent Unicode sequences hash identically. */
function toNFC(value: string): string {
  // `String.prototype.normalize` is available in all targeted runtimes; guard
  // defensively in case of an exotic host that lacks it.
  return typeof value.normalize === 'function' ? value.normalize('NFC') : value;
}

/**
 * Serialize a RegExp to a stable string that includes its flags.
 * `toString()` yields `/source/flags`, which round-trips flags that
 * `RegExp.source` would otherwise drop.
 */
function serializeRegExp(pattern: RegExp): string {
  return toNFC(pattern.toString());
}

/**
 * Build the canonical JSON-safe snapshot of a resolved config.
 * Exported primarily for testing and diagnostics.
 */
export function toSelectorConfigSnapshot(config: ResolvedSelectorConfig): SelectorConfigSnapshot {
  return {
    enabled: config.enabled,
    explicitTrackingAttribute: toNFC(config.explicitTrackingAttribute),
    autogeneratedIdPatterns: config.autogeneratedIdPatterns.map(serializeRegExp),
    unstableClassPatterns: config.unstableClassPatterns.map(serializeRegExp),
    maxAncestorWalkDepth: config.maxAncestorWalkDepth === undefined ? null : config.maxAncestorWalkDepth,
  };
}

/**
 * Produce the RFC 8785 (JCS) canonical JSON string for a resolved config.
 *
 * Stable across key insertion order and across the omitted-vs-explicit-default
 * distinction. Useful on its own for debugging "why did the hash change?".
 */
export function canonicalizeSelectorConfig(config: ResolvedSelectorConfig): string {
  const snapshot = toSelectorConfigSnapshot(config);
  // `canonicalize` returns `undefined` only for `undefined`/function inputs; our
  // snapshot is always a populated object, so the `?? ''` branch is a defensive
  // fallback that should be unreachable in practice.
  /* istanbul ignore next */
  return canonicalize(snapshot) ?? '';
}

/**
 * Compute the stable SHA-256 hash (lowercase hex) of a resolved selector config.
 *
 * This is the value tracked as `[Amplitude] Selector Algo Config Hash`. It is
 * synchronous so it can be attached on the synchronous event-tracking path
 * without caching or secure-context concerns.
 *
 * @param config - The fully-resolved selector config (defaults applied).
 * @returns 64-character lowercase hex SHA-256 digest.
 */
export function hashSelectorConfig(config: ResolvedSelectorConfig): string {
  return sha256Hex(canonicalizeSelectorConfig(config));
}
