import { createHash } from 'crypto';
import { hashSelectorConfig, canonicalizeSelectorConfig, toSelectorConfigSnapshot } from '../../src/config/hash-config';
import { resolveSelectorConfig } from '../../src/config/resolve-config';
import { ResolvedSelectorConfig } from '../../src/types';

const baseConfig = (): ResolvedSelectorConfig => ({
  enabled: true,
  explicitTrackingAttribute: 'data-amp-track-id',
  autogeneratedIdPatterns: [/^:r[0-9a-z]+:$/, /^[a-f0-9]{16,}$/i],
  unstableClassPatterns: [/^css-[a-z0-9]{6,}$/],
  maxAncestorWalkDepth: 5,
});

describe('toSelectorConfigSnapshot', () => {
  it('projects the resolved config into a fully-specified JSON-safe shape', () => {
    expect(toSelectorConfigSnapshot(baseConfig())).toEqual({
      enabled: true,
      explicitTrackingAttribute: 'data-amp-track-id',
      autogeneratedIdPatterns: ['/^:r[0-9a-z]+:$/', '/^[a-f0-9]{16,}$/i'],
      unstableClassPatterns: ['/^css-[a-z0-9]{6,}$/'],
      maxAncestorWalkDepth: 5,
    });
  });

  it('serializes RegExp flags (toString, not source) so flags are part of the fingerprint', () => {
    const snapshot = toSelectorConfigSnapshot({
      ...baseConfig(),
      autogeneratedIdPatterns: [/abc/i, /abc/],
    });
    expect(snapshot.autogeneratedIdPatterns).toEqual(['/abc/i', '/abc/']);
  });

  it('normalizes an undefined maxAncestorWalkDepth to null', () => {
    const snapshot = toSelectorConfigSnapshot({ ...baseConfig(), maxAncestorWalkDepth: undefined });
    expect(snapshot.maxAncestorWalkDepth).toBeNull();
  });
});

describe('canonicalizeSelectorConfig', () => {
  it('emits RFC 8785 canonical JSON with lexicographically sorted keys and no whitespace', () => {
    const canonical = canonicalizeSelectorConfig(baseConfig());
    expect(canonical).toBe(
      '{"autogeneratedIdPatterns":["/^:r[0-9a-z]+:$/","/^[a-f0-9]{16,}$/i"],' +
        '"enabled":true,' +
        '"explicitTrackingAttribute":"data-amp-track-id",' +
        '"maxAncestorWalkDepth":5,' +
        '"unstableClassPatterns":["/^css-[a-z0-9]{6,}$/"]}',
    );
    expect(canonical).not.toMatch(/\s/);
  });
});

describe('hashSelectorConfig', () => {
  it('returns a 64-character lowercase hex SHA-256 digest', () => {
    expect(hashSelectorConfig(baseConfig())).toMatch(/^[0-9a-f]{64}$/);
  });

  it('is the SHA-256 of the canonical string', () => {
    const config = baseConfig();
    const expected = createHash('sha256').update(canonicalizeSelectorConfig(config), 'utf8').digest('hex');
    expect(hashSelectorConfig(config)).toBe(expected);
  });

  it('is deterministic for the same config', () => {
    expect(hashSelectorConfig(baseConfig())).toBe(hashSelectorConfig(baseConfig()));
  });

  describe('defaults: omitted vs. explicit produce the same hash', () => {
    it('no remote payload === empty remote payload', () => {
      expect(hashSelectorConfig(resolveSelectorConfig())).toBe(hashSelectorConfig(resolveSelectorConfig({})));
    });

    it('omitting `enabled` === explicitly setting it to the default (false)', () => {
      expect(hashSelectorConfig(resolveSelectorConfig({}))).toBe(
        hashSelectorConfig(resolveSelectorConfig({ enabled: false })),
      );
    });

    it('omitting depth === providing an out-of-range depth (both resolve to no-limit)', () => {
      // resolveSelectorConfig coerces <= 0 to undefined → snapshot null.
      expect(hashSelectorConfig(resolveSelectorConfig({}))).toBe(
        hashSelectorConfig(resolveSelectorConfig({ maxAncestorWalkDepth: 0 })),
      );
    });
  });

  describe('Unicode normalization (NFC)', () => {
    it('hashes NFD and NFC forms of the tracking attribute identically', () => {
      // "café": precomposed é (U+00E9) vs decomposed e + combining acute (U+0301).
      const nfc = 'caf\u00e9';
      const nfd = 'cafe\u0301';
      expect(nfc).not.toBe(nfd); // different code-point sequences
      const hashNfc = hashSelectorConfig({ ...baseConfig(), explicitTrackingAttribute: nfc });
      const hashNfd = hashSelectorConfig({ ...baseConfig(), explicitTrackingAttribute: nfd });
      expect(hashNfc).toBe(hashNfd);
    });
  });

  describe('sensitivity — different configs produce different hashes', () => {
    const base = baseConfig();
    const baseHash = hashSelectorConfig(base);

    it('changes when `enabled` flips', () => {
      expect(hashSelectorConfig({ ...base, enabled: false })).not.toBe(baseHash);
    });

    it('changes when the tracking attribute changes', () => {
      expect(hashSelectorConfig({ ...base, explicitTrackingAttribute: 'data-track' })).not.toBe(baseHash);
    });

    it('changes when an autogenerated-id pattern changes', () => {
      expect(hashSelectorConfig({ ...base, autogeneratedIdPatterns: [/^different/] })).not.toBe(baseHash);
    });

    it('changes when an unstable-class pattern changes', () => {
      expect(hashSelectorConfig({ ...base, unstableClassPatterns: [/^different/] })).not.toBe(baseHash);
    });

    it('changes when maxAncestorWalkDepth changes', () => {
      expect(hashSelectorConfig({ ...base, maxAncestorWalkDepth: 6 })).not.toBe(baseHash);
    });

    it('changes when a pattern differs only by RegExp flags', () => {
      const ci = hashSelectorConfig({ ...base, autogeneratedIdPatterns: [/abc/i] });
      const cs = hashSelectorConfig({ ...base, autogeneratedIdPatterns: [/abc/] });
      expect(ci).not.toBe(cs);
    });

    it('changes when pattern array order changes (order is part of the config)', () => {
      const ordered = hashSelectorConfig({ ...base, autogeneratedIdPatterns: [/^a/, /^b/] });
      const reordered = hashSelectorConfig({ ...base, autogeneratedIdPatterns: [/^b/, /^a/] });
      expect(ordered).not.toBe(reordered);
    });
  });
});
