import { resolveSelectorConfig, DEFAULT_RESOLVED_CONFIG } from '../../src/config/resolve-config';
import { DEFAULT_AUTOGENERATED_ID_PATTERNS } from '../../src/patterns/autogenerated-ids';
import { DEFAULT_UNSTABLE_CLASS_PATTERNS } from '../../src/patterns/unstable-classes';

describe('resolveSelectorConfig', () => {
  describe('no remote payload', () => {
    it('returns a config with the documented defaults', () => {
      const cfg = resolveSelectorConfig();
      expect(cfg.enabled).toBe(false);
      expect(cfg.explicitTrackingAttribute).toBe('data-amp-track-id');
      expect(cfg.autogeneratedIdPatterns).toEqual([...DEFAULT_AUTOGENERATED_ID_PATTERNS]);
      expect(cfg.unstableClassPatterns).toEqual([...DEFAULT_UNSTABLE_CLASS_PATTERNS]);
      expect(cfg.maxAncestorWalkDepth).toBeUndefined();
    });

    it('returns a fresh object — callers can safely mutate it', () => {
      const cfg = resolveSelectorConfig();
      cfg.autogeneratedIdPatterns.push(/^safely-added/);
      // DEFAULT_RESOLVED_CONFIG.autogeneratedIdPatterns is a frozen snapshot;
      // a fresh resolve should NOT see the mutation.
      const cfg2 = resolveSelectorConfig();
      expect(cfg2.autogeneratedIdPatterns).toEqual([...DEFAULT_AUTOGENERATED_ID_PATTERNS]);
    });
  });

  describe('enabled flag', () => {
    it('respects an explicit true', () => {
      expect(resolveSelectorConfig({ enabled: true }).enabled).toBe(true);
    });

    it('respects an explicit false (does not silently fall back to default false)', () => {
      // This is the same as the default but matters as an explicit signal —
      // remote config saying "off" should be honored, not erased.
      expect(resolveSelectorConfig({ enabled: false }).enabled).toBe(false);
    });

    it('ignores non-boolean values', () => {
      // Defensive — remote payloads can be garbage. We default rather than coerce.
      const cfg = resolveSelectorConfig({ enabled: 'yes' as unknown as boolean });
      expect(cfg.enabled).toBe(false);
    });
  });

  describe('explicitTrackingAttribute', () => {
    it('accepts a non-empty custom value', () => {
      expect(resolveSelectorConfig({ explicitTrackingAttribute: 'data-track' }).explicitTrackingAttribute).toBe(
        'data-track',
      );
    });

    it('rejects an empty string and falls back to the default', () => {
      // An empty string would make the strategy treat every element as
      // anchorable — reject and fall back.
      expect(resolveSelectorConfig({ explicitTrackingAttribute: '' }).explicitTrackingAttribute).toBe(
        'data-amp-track-id',
      );
    });
  });

  describe('autogeneratedIdPatterns — full replacement, not merge', () => {
    it('compiles the remote-provided list and uses it as-is', () => {
      const cfg = resolveSelectorConfig({ autogeneratedIdPatterns: ['^acme-id-', '\\d{5,}'] });
      expect(cfg.autogeneratedIdPatterns).toHaveLength(2);
      expect(cfg.autogeneratedIdPatterns[0].test('acme-id-foo')).toBe(true);
      expect(cfg.autogeneratedIdPatterns[1].test('12345')).toBe(true);
    });

    it('accepts an empty list as an explicit "disable autogen filtering" signal', () => {
      // Critically: empty list ≠ "use defaults". The customer wants the filter off.
      const cfg = resolveSelectorConfig({ autogeneratedIdPatterns: [] });
      expect(cfg.autogeneratedIdPatterns).toEqual([]);
    });

    it('silently drops invalid regex strings rather than throwing', () => {
      const cfg = resolveSelectorConfig({ autogeneratedIdPatterns: ['^valid$', '[unclosed', '^also-valid$'] });
      expect(cfg.autogeneratedIdPatterns).toHaveLength(2);
    });
  });

  describe('unstableClassPatterns — full replacement, not merge', () => {
    it('compiles the remote-provided list and uses it as-is', () => {
      const cfg = resolveSelectorConfig({ unstableClassPatterns: ['^acme-', '^foo-bar$'] });
      expect(cfg.unstableClassPatterns).toHaveLength(2);
      expect(cfg.unstableClassPatterns[0].test('acme-anything')).toBe(true);
    });

    it('accepts an empty list as an explicit "disable filtering" signal', () => {
      const cfg = resolveSelectorConfig({ unstableClassPatterns: [] });
      expect(cfg.unstableClassPatterns).toEqual([]);
    });
  });

  describe('maxAncestorWalkDepth clamp', () => {
    it('passes through positive integers', () => {
      expect(resolveSelectorConfig({ maxAncestorWalkDepth: 5 }).maxAncestorWalkDepth).toBe(5);
    });

    it('floors positive floats to integers', () => {
      expect(resolveSelectorConfig({ maxAncestorWalkDepth: 4.9 }).maxAncestorWalkDepth).toBe(4);
    });

    it('coerces zero to undefined (no limit)', () => {
      expect(resolveSelectorConfig({ maxAncestorWalkDepth: 0 }).maxAncestorWalkDepth).toBeUndefined();
    });

    it('coerces negatives to undefined (no limit)', () => {
      expect(resolveSelectorConfig({ maxAncestorWalkDepth: -10 }).maxAncestorWalkDepth).toBeUndefined();
    });

    it('coerces NaN to undefined', () => {
      expect(resolveSelectorConfig({ maxAncestorWalkDepth: NaN }).maxAncestorWalkDepth).toBeUndefined();
    });

    it('coerces Infinity to undefined', () => {
      expect(resolveSelectorConfig({ maxAncestorWalkDepth: Infinity }).maxAncestorWalkDepth).toBeUndefined();
    });
  });

  describe('partial overrides leave defaults intact for absent fields', () => {
    it('overriding `enabled` keeps the default attribute name and pattern packs', () => {
      const cfg = resolveSelectorConfig({ enabled: true });
      expect(cfg.enabled).toBe(true);
      expect(cfg.explicitTrackingAttribute).toBe('data-amp-track-id');
      expect(cfg.autogeneratedIdPatterns).toEqual([...DEFAULT_AUTOGENERATED_ID_PATTERNS]);
    });
  });

  describe('DEFAULT_RESOLVED_CONFIG snapshot', () => {
    it('is frozen to prevent accidental mutation', () => {
      expect(Object.isFrozen(DEFAULT_RESOLVED_CONFIG)).toBe(true);
    });
  });
});
