/**
 * Schema-vs-type drift guard.
 *
 * The JSON Schema at `schema/element-selector-remote-config.schema.json` is the
 * canonical contract shared by backend remote-config, the SDK at runtime, and
 * the dashboard's remote-config editor. The TypeScript `ElementSelectorRemoteConfig`
 * interface in `src/types.ts` is the contract the SDK exposes to consumers.
 *
 * These two artifacts MUST stay structurally aligned. This test catches the
 * common drift cases:
 *   - A new field added to the TS type but not the schema (or vice-versa)
 *   - A field's type changing on one side
 *   - `additionalProperties: false` accidentally becoming permissive
 *
 * We don't pull in `ajv` or `json-schema-to-typescript` for this PR — those
 * are larger dependencies than the small surface area justifies. A
 * hand-rolled structural assertion is enough to catch drift in CI.
 */
import * as fs from 'fs';
import * as path from 'path';
import type { ElementSelectorRemoteConfig } from '../../src/types';

interface JsonSchema {
  type?: string;
  additionalProperties?: boolean;
  properties?: Record<string, JsonSchemaProperty>;
  examples?: unknown[];
}

interface JsonSchemaProperty {
  type: string | string[];
  items?: { type: string };
  minimum?: number;
  minLength?: number;
}

const schemaPath = path.resolve(__dirname, '../../schema/element-selector-remote-config.schema.json');
const schema = JSON.parse(fs.readFileSync(schemaPath, 'utf-8')) as JsonSchema;

describe('element-selector-remote-config schema', () => {
  describe('shape sanity', () => {
    it('is a JSON object schema', () => {
      expect(schema.type).toBe('object');
    });

    it('forbids additional properties — drift guard against accidental opening of the schema', () => {
      expect(schema.additionalProperties).toBe(false);
    });

    it('declares all five known fields and no others', () => {
      const fields = Object.keys(schema.properties ?? {}).sort();
      expect(fields).toEqual(
        [
          'autogeneratedIdPatterns',
          'enabled',
          'explicitTrackingAttribute',
          'maxAncestorWalkDepth',
          'unstableClassPatterns',
        ].sort(),
      );
    });
  });

  describe('per-field types', () => {
    it('enabled is boolean', () => {
      expect(schema.properties?.enabled.type).toBe('boolean');
    });

    it('explicitTrackingAttribute is a non-empty string', () => {
      const prop = schema.properties?.explicitTrackingAttribute;
      expect(prop?.type).toBe('string');
      expect(prop?.minLength).toBe(1);
    });

    it('autogeneratedIdPatterns is an array of strings', () => {
      const prop = schema.properties?.autogeneratedIdPatterns;
      expect(prop?.type).toBe('array');
      expect(prop?.items?.type).toBe('string');
    });

    it('unstableClassPatterns is an array of strings', () => {
      const prop = schema.properties?.unstableClassPatterns;
      expect(prop?.type).toBe('array');
      expect(prop?.items?.type).toBe('string');
    });

    it('maxAncestorWalkDepth is a positive integer', () => {
      const prop = schema.properties?.maxAncestorWalkDepth;
      expect(prop?.type).toBe('integer');
      expect(prop?.minimum).toBe(1);
    });
  });

  describe('TS type ↔ schema property name parity', () => {
    /*
     * Every property in the JSON Schema must correspond to a field in the
     * `ElementSelectorRemoteConfig` TypeScript interface and vice-versa.
     *
     * Strategy: build a typed value that lists every known field, then check
     * the schema's `properties` map against the keys of that object. TypeScript
     * itself enforces that the value matches the interface, so if a field is
     * added to the interface without being added here, the file stops
     * compiling — and if it's added to the schema but not the interface,
     * `Object.keys(reference)` won't include it.
     */
    const reference: Required<{ [K in keyof ElementSelectorRemoteConfig]-?: true }> = {
      enabled: true,
      explicitTrackingAttribute: true,
      autogeneratedIdPatterns: true,
      unstableClassPatterns: true,
      maxAncestorWalkDepth: true,
    };

    it('every TS field is in the schema', () => {
      for (const field of Object.keys(reference)) {
        expect(schema.properties).toHaveProperty(field);
      }
    });

    it('every schema field is in the TS type', () => {
      for (const field of Object.keys(schema.properties ?? {})) {
        expect(reference).toHaveProperty(field);
      }
    });
  });

  describe('examples', () => {
    it('includes representative examples for the remote-config UI', () => {
      expect(schema.examples).toBeDefined();
      expect(Array.isArray(schema.examples)).toBe(true);
      expect((schema.examples ?? []).length).toBeGreaterThanOrEqual(2);
    });
  });
});
