import { expect, test } from '@playwright/test';

test('audits exposure allowlist, selector uniqueness, and generated ID patterns', async ({ page }) => {
  await page.goto('/autocapture/client-exposure-audit.html');
  await expect(page.locator('#status')).toHaveText('ready');
  await page.waitForTimeout(300);

  const report = await page.evaluate(() => {
    window.AmplitudeExposureAudit.snapshot('initial');
    return window.AmplitudeExposureAudit.report();
  });

  expect(report.summary).toMatchObject({
    scenarios: 1,
    likelyInteractive: 3,
    allowlisted: 2,
    missingFromAllowlist: 1,
    exposed: 2,
    nonUniqueSelectors: 0,
    selectorsThatMissTarget: 0,
    unstableSelectorGroups: 0,
  });
  expect(report.missingFromAllowlist).toEqual([
    expect.objectContaining({
      id: 'custom-control',
      role: 'button',
      selector: 'div#custom-control',
    }),
  ]);
  expect(report.patternSuggestions).toEqual([
    expect.objectContaining({
      kind: 'autogeneratedId',
      pattern: '^client-widget-',
      evidence: expect.arrayContaining(['client-widget-a1b2c3d4', 'client-widget-e5f6a7b8']),
    }),
  ]);
  expect(report.scenarios[0].newlyExposed).toEqual(
    expect.arrayContaining(['button#client-widget-a1b2c3d4', 'button#client-widget-e5f6a7b8']),
  );
});

test('compares SDK defaults against the settings it recommends', async ({ page }) => {
  await page.goto('/autocapture/client-exposure-audit.html');
  await expect(page.locator('#status')).toHaveText('ready');
  await page.waitForTimeout(300);

  const { settings } = await page.evaluate(() => {
    window.AmplitudeExposureAudit.snapshot('initial');
    return window.AmplitudeExposureAudit.report();
  });

  expect(settings.sdkDefaults.elementSelector).toMatchObject({
    enabled: false,
    shadowDomEnabled: false,
    maxShadowDomDepth: 1,
  });
  expect(settings.hasRecommendedChanges).toBe(true);
  // The fixture installs with stock settings, so only harness-controlled fields differ.
  expect(settings.auditedCustomizations).toEqual([]);
  expect(settings.auditedMatchesSdkDefaults).toBe(true);

  const byField = Object.fromEntries(settings.changes.map((change) => [change.field, change]));

  expect(byField['cssSelectorAllowlist']).toMatchObject({
    kind: 'list',
    changed: true,
    added: ['[role="button" i]'],
    removed: [],
  });
  expect(settings.allowlistAdditions).toEqual([
    expect.objectContaining({ selector: '[role="button" i]', matchedElements: 1, broad: false }),
  ]);

  expect(byField['elementSelector.enabled']).toMatchObject({ changed: true, recommended: true });
  // The fixture has no shadow roots, so piercing stays at the SDK default.
  expect(byField['elementSelector.shadowDomEnabled']).toMatchObject({ changed: false, recommended: false });
  expect(byField['elementSelector.maxShadowDomDepth']).toMatchObject({ changed: false, recommended: 1 });
  expect(byField['exposureDuration']).toMatchObject({ changed: false, recommended: 150 });

  expect(byField['elementSelector.autogeneratedIdPatterns']).toMatchObject({
    kind: 'list',
    changed: true,
    added: ['^client-widget-'],
    removed: [],
  });
  // Pattern arrays replace the defaults, so the recommendation carries them forward.
  expect(settings.recommended.elementSelector.autogeneratedIdPatterns).toEqual([
    ...settings.sdkDefaults.elementSelector.autogeneratedIdPatterns,
    '^client-widget-',
  ]);

  expect(settings.apply.remoteConfigKey).toBe('configs.analyticsSDK.browserSDK.autocapture.elementSelector');
  expect(settings.apply.remoteConfigPayload).toEqual(settings.recommended.elementSelector);
  expect(settings.apply.sdkOptions.cssSelectorAllowlist).toEqual(settings.recommended.cssSelectorAllowlist);
});
