import { expect, test } from '@playwright/test';

test('audits exposure allowlist, selector uniqueness, and generated ID patterns', async ({ page }) => {
  await page.goto('/autocapture/client-exposure-audit.html');
  await expect(page.locator('#status')).toHaveText('ready');
  await page.waitForTimeout(100);

  const report = await page.evaluate(() => {
    window.AmplitudeExposureAudit.snapshot('initial');
    return window.AmplitudeExposureAudit.report();
  });

  expect(report.summary).toMatchObject({
    scenarios: 1,
    likelyInteractive: 3,
    allowlisted: 2,
    missingFromAllowlist: 1,
    exposed: 2,
    nonUniqueSelectors: 0,
    selectorsThatMissTarget: 0,
    unstableSelectorGroups: 0,
  });
  expect(report.missingFromAllowlist).toEqual([
    expect.objectContaining({
      id: 'custom-control',
      role: 'button',
      selector: 'div#custom-control',
    }),
  ]);
  expect(report.patternSuggestions).toEqual([
    expect.objectContaining({
      kind: 'autogeneratedId',
      pattern: '^client-widget-',
      evidence: expect.arrayContaining(['client-widget-a1b2c3d4', 'client-widget-e5f6a7b8']),
    }),
  ]);
  expect(report.scenarios[0].newlyExposed).toEqual(
    expect.arrayContaining(['button#client-widget-a1b2c3d4', 'button#client-widget-e5f6a7b8']),
  );
});
