import { DEFAULT_CSS_SELECTOR_ALLOWLIST, DEFAULT_EXPOSURE_DURATION, multicast } from '@amplitude/analytics-core';
import {
  createSelectorEngine,
  DEFAULT_AUTOGENERATED_ID_PATTERNS,
  DEFAULT_UNSTABLE_CLASS_PATTERNS,
  resolveSelector,
  resolveSelectorConfig,
  SHADOW_BOUNDARY_DELIMITER,
  type ElementSelectorRemoteConfig,
} from '@amplitude/element-selector';
import { ObservablesEnum, type AllWindowObservables } from '../src/autocapture-plugin';
import { trackExposure } from '../src/autocapture/track-exposure';
import { DataExtractor } from '../src/data-extractor';
import { ELEMENT_SELECTOR_REMOTE_CONFIG_KEY } from '../src/element-selector-config';
import { createExposureObservable, createMutationObservable, createScrollObservable } from '../src/observables';

declare global {
  interface Window {
    AmplitudeExposureAudit: {
      install: typeof install;
      snapshot: typeof snapshot;
      report: typeof report;
    };
  }
}

const LIKELY_INTERACTIVE_SELECTORS = [
  'a[href]',
  'button',
  'input:not([type="hidden"])',
  'select',
  'textarea',
  'label',
  'summary',
  '[contenteditable="true" i]',
  '[onclick]',
  '[role="button" i]',
  '[role="checkbox" i]',
  '[role="combobox" i]',
  '[role="link" i]',
  '[role="menuitem" i]',
  '[role="option" i]',
  '[role="radio" i]',
  '[role="slider" i]',
  '[role="switch" i]',
  '[role="tab" i]',
  '[tabindex]:not([tabindex="-1"])',
];

/**
 * Catch-all selectors that match interactive elements without saying anything
 * about what they are. They are proposed for the allowlist only when nothing
 * more specific covers an element, and are flagged as broad in the report.
 */
const BROAD_INTERACTIVE_SELECTORS = ['[onclick]', '[tabindex]:not([tabindex="-1"])'];

type AuditOptions = {
  allowlist?: string[];
  elementSelector?: ElementSelectorRemoteConfig;
  exposureDuration?: number;
};

type ElementRecord = {
  instanceId: number;
  key: string;
  tag: string;
  text: string;
  role: string | null;
  id: string | null;
  classes: string[];
  allowlisted: boolean;
  likelyInteractive: boolean;
  interactiveReasons: string[];
  selector: string;
  matchCount: number;
  resolvesToTarget: boolean;
};

type ScenarioRecord = {
  name: string;
  url: string;
  scrollX: number;
  scrollY: number;
  viewport: { width: number; height: number };
  newlyExposed: string[];
  exposed: string[];
  elements: ElementRecord[];
};

type PatternSuggestion = {
  kind: 'autogeneratedId' | 'unstableClass';
  pattern: string;
  evidence: string[];
  reason: string;
};

/**
 * One complete set of settings, in the same shape regardless of whether it is
 * the SDK baseline, what the audit ran with, or what the audit recommends.
 * Keeping the three in one shape is what makes them diffable side by side.
 */
type ConfigSnapshot = {
  cssSelectorAllowlist: string[];
  exposureDuration: number;
  elementSelector: {
    enabled: boolean;
    shadowDomEnabled: boolean;
    maxShadowDomDepth: number;
    autogeneratedIdPatterns: string[];
    unstableClassPatterns: string[];
  };
};

/**
 * Shared by both change kinds. `harnessControlled` marks the fields the harness
 * must override to do its job, so an audited value that differs from the SDK
 * default there says nothing about how the customer is configured.
 */
type ChangeBase = {
  field: string;
  changed: boolean;
  harnessControlled: boolean;
  reason: string;
};

type ConfigValue = string[] | number | boolean;

type ScalarChange = ChangeBase & {
  kind: 'value';
  sdkDefault: number | boolean;
  audited: number | boolean;
  recommended: number | boolean;
};

/**
 * List fields carry only the delta. The full arrays live once each in
 * `sdkDefaults`, `audited`, and `recommended` rather than three more times here.
 */
type ListChange = ChangeBase & {
  kind: 'list';
  entryCount: { sdkDefault: number; audited: number; recommended: number };
  added: string[];
  removed: string[];
};

type ConfigChange = ScalarChange | ListChange;

type AllowlistAddition = {
  selector: string;
  matchedElements: number;
  broad: boolean;
  examples: string[];
  reason: string;
};

type SettingsComparison = {
  hasRecommendedChanges: boolean;
  auditedMatchesSdkDefaults: boolean;
  auditedCustomizations: string[];
  sdkDefaults: ConfigSnapshot;
  audited: ConfigSnapshot;
  recommended: ConfigSnapshot;
  changes: ConfigChange[];
  allowlistAdditions: AllowlistAddition[];
  apply: {
    remoteConfigKey: string;
    remoteConfigPayload: ConfigSnapshot['elementSelector'];
    sdkOptions: { cssSelectorAllowlist: string[]; exposureDuration: number };
  };
  notes: string[];
};

type AuditReport = {
  url: string;
  title: string;
  generatedAt: string;
  settings: SettingsComparison;
  summary: {
    scenarios: number;
    likelyInteractive: number;
    allowlisted: number;
    missingFromAllowlist: number;
    exposed: number;
    nonUniqueSelectors: number;
    selectorsThatMissTarget: number;
    unstableSelectorGroups: number;
    patternSuggestions: number;
    recommendedChanges: number;
  };
  missingFromAllowlist: ElementRecord[];
  selectorProblems: ElementRecord[];
  unstableSelectorGroups: Array<{ key: string; selectors: string[] }>;
  patternSuggestions: PatternSuggestion[];
  scenarios: ScenarioRecord[];
};

type Harness = {
  options: Required<Pick<AuditOptions, 'allowlist' | 'exposureDuration'>> & {
    elementSelector: ElementSelectorRemoteConfig;
  };
  engine: ReturnType<typeof createSelectorEngine>;
  extractor: DataExtractor;
  exposureTracker: ReturnType<typeof trackExposure>;
  exposed: Set<string>;
  lastSnapshotExposed: Set<string>;
  scenarios: ScenarioRecord[];
};

let harness: Harness | undefined;
let nextElementInstanceId = 1;
let elementInstanceIds = new WeakMap<Element, number>();

const instanceIdOf = (element: Element): number => {
  const existing = elementInstanceIds.get(element);
  if (existing) return existing;
  const next = nextElementInstanceId;
  nextElementInstanceId += 1;
  elementInstanceIds.set(element, next);
  return next;
};

const textOf = (element: Element): string =>
  (element.getAttribute('aria-label') || element.textContent || '').replace(/\s+/g, ' ').trim().slice(0, 120);

const elementKey = (element: Element): string =>
  [
    element.tagName.toLowerCase(),
    element.getAttribute('role') || '',
    element.getAttribute('name') || '',
    element.getAttribute('aria-label') || '',
    textOf(element),
  ].join('|');

const matchedSelectors = (element: Element, selectors: string[]): string[] =>
  selectors.filter((selector) => {
    try {
      return element.matches(selector);
    } catch {
      return false;
    }
  });

const matchesAny = (element: Element, selectors: string[]): boolean => matchedSelectors(element, selectors).length > 0;

const collectElements = (root: Document | ShadowRoot = document): Element[] => {
  const elements: Element[] = [];
  root.querySelectorAll('*').forEach((element) => {
    if (element.closest('[data-amplitude-exposure-audit]')) return;
    elements.push(element);
    if (element.shadowRoot) {
      elements.push(...collectElements(element.shadowRoot));
    }
  });
  return elements;
};

const selectorMatchCount = (selector: string): number => {
  const segments = selector.split(SHADOW_BOUNDARY_DELIMITER).map((segment) => segment.trim());
  let scope: ParentNode | null = document;
  for (let index = 0; index < segments.length; index += 1) {
    if (!scope) return 0;
    const segment = segments[index];
    if (segment.startsWith(':scope >')) {
      const steps = segment
        .slice(':scope >'.length)
        .split('>')
        .map((step) => step.trim());
      let candidates = Array.from(scope.children);
      let found: Element[] = [];
      for (const step of steps) {
        found = candidates.filter((candidate) => candidate.matches(step));
        if (found.length !== 1) return found.length;
        candidates = Array.from(found[0].children);
      }
      if (index === segments.length - 1) return found.length;
      scope = found[0]?.shadowRoot ?? null;
      continue;
    }
    let matches: Element[];
    try {
      matches = Array.from(scope.querySelectorAll(segment));
    } catch {
      return 0;
    }
    if (index === segments.length - 1) return matches.length;
    if (matches.length !== 1) return matches.length;
    scope = matches[0].shadowRoot;
  }
  return 0;
};

const describe = (element: Element, activeHarness: Harness): ElementRecord => {
  const selector = activeHarness.engine.generate(element);
  const resolved = resolveSelector(document, selector);
  const interactiveReasons = matchedSelectors(element, LIKELY_INTERACTIVE_SELECTORS);
  return {
    instanceId: instanceIdOf(element),
    key: elementKey(element),
    tag: element.tagName.toLowerCase(),
    text: textOf(element),
    role: element.getAttribute('role'),
    id: element.id || null,
    classes: Array.from(element.classList),
    allowlisted: matchesAny(element, activeHarness.options.allowlist),
    likelyInteractive: interactiveReasons.length > 0,
    interactiveReasons,
    selector,
    matchCount: selectorMatchCount(selector),
    resolvesToTarget: resolved === element,
  };
};

const source = (pattern: RegExp): string => pattern.source;

const commonPrefix = (values: string[]): string => {
  if (values.length === 0) return '';
  let prefix = values[0];
  for (const value of values.slice(1)) {
    while (prefix && !value.startsWith(prefix)) prefix = prefix.slice(0, -1);
  }
  return prefix;
};

const escapeRegex = (value: string): string => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

const looksGenerated = (value: string): boolean =>
  /[a-f0-9]{8}-[a-f0-9-]{20,}/i.test(value) ||
  /(?:^|[-_])[a-f0-9]{8,}(?:[-_]|$)/i.test(value) ||
  /(?:^|[-_])(?=[a-z0-9]{10,}(?:[-_]|$))(?=[a-z0-9]*[a-z])(?=[a-z0-9]*\d)[a-z0-9]+(?:[-_]|$)/i.test(value) ||
  /__[A-Za-z0-9_]+__[A-Za-z0-9]{5,}$/.test(value);

const generatedPrefix = (value: string): string => {
  const token = value.match(
    /(?:^|[-_])(?:[a-f0-9]{8,}|(?=[a-z0-9]{10,}(?:[-_]|$))(?=[a-z0-9]*[a-z])(?=[a-z0-9]*\d)[a-z0-9]+)(?=[-_]|$)/i,
  );
  if (!token || token.index === undefined) return '';
  const delimiterLength = token[0].startsWith('-') || token[0].startsWith('_') ? 1 : 0;
  return value.slice(0, token.index + delimiterLength);
};

const patternSuggestions = (scenarios: ScenarioRecord[], config: ReturnType<typeof resolveSelectorConfig>) => {
  const suggestions: PatternSuggestion[] = [];
  const all = scenarios.flatMap((scenario) => scenario.elements);
  const ids = Array.from(
    new Set(all.map((element) => element.id).filter((id): id is string => typeof id === 'string' && id.length > 0)),
  );
  const uncoveredIds = ids.filter(
    (id) => looksGenerated(id) && !config.autogeneratedIdPatterns.some((pattern) => Boolean(pattern.test(id))),
  );

  const idGroups = new Map<string, string[]>();
  uncoveredIds.forEach((id) => {
    const prefix = generatedPrefix(id);
    if (!prefix) return;
    idGroups.set(prefix, [...(idGroups.get(prefix) ?? []), id]);
  });
  idGroups.forEach((evidence, prefix) => {
    if (evidence.length < 2) return;
    suggestions.push({
      kind: 'autogeneratedId',
      pattern: `^${escapeRegex(prefix)}`,
      evidence: evidence.slice(0, 10),
      reason: 'Multiple generated-looking IDs share this prefix and are not covered by the active patterns.',
    });
  });

  const recordsByInstance = new Map<number, ElementRecord[]>();
  all.forEach((record) =>
    recordsByInstance.set(record.instanceId, [...(recordsByInstance.get(record.instanceId) ?? []), record]),
  );
  recordsByInstance.forEach((records) => {
    const variants = Array.from(
      new Set(records.map((record) => record.id).filter((id): id is string => typeof id === 'string' && id.length > 0)),
    );
    if (
      variants.length < 2 ||
      variants.every((id) => config.autogeneratedIdPatterns.some((pattern) => Boolean(pattern.test(id))))
    ) {
      return;
    }
    const prefix = commonPrefix(variants).replace(/[A-Za-z0-9]+$/, '');
    if (prefix.length < 3) return;
    suggestions.push({
      kind: 'autogeneratedId',
      pattern: `^${escapeRegex(prefix)}`,
      evidence: variants.slice(0, 10),
      reason: 'The same semantic component produced different IDs between scenarios.',
    });
  });

  const classesByKey = new Map<string, string[]>();
  recordsByInstance.forEach((records) => {
    const classSets = Array.from(new Set(records.map((record) => [...record.classes].sort().join(' '))));
    if (classSets.length < 2) return;
    const occurrenceCount = new Map<string, number>();
    records.forEach((record) => {
      new Set(record.classes).forEach((className) =>
        occurrenceCount.set(className, (occurrenceCount.get(className) ?? 0) + 1),
      );
    });
    const changingClasses = Array.from(occurrenceCount)
      .filter(([, count]) => count < records.length)
      .map(([className]) => className);
    if (changingClasses.length) classesByKey.set(records[0].key, changingClasses);
  });
  classesByKey.forEach((classes) => {
    const uncovered = classes.filter(
      (className) =>
        looksGenerated(className) && !config.unstableClassPatterns.some((pattern) => Boolean(pattern.test(className))),
    );
    const prefix = commonPrefix(uncovered).replace(/[A-Za-z0-9]+$/, '');
    if (uncovered.length < 2 || prefix.length < 3) return;
    suggestions.push({
      kind: 'unstableClass',
      pattern: `^${escapeRegex(prefix)}`,
      evidence: uncovered.slice(0, 10),
      reason:
        'Generated-looking class variants appear on the same semantic component. The current v1 selector does not emit classes, but this pattern protects class-aware consumers.',
    });
  });

  return suggestions.filter(
    (suggestion, index) =>
      suggestions.findIndex(
        (candidate) => candidate.kind === suggestion.kind && candidate.pattern === suggestion.pattern,
      ) === index,
  );
};

/** The settings a customer gets when they change nothing. */
const sdkDefaults = (): ConfigSnapshot => {
  const resolved = resolveSelectorConfig();
  return {
    cssSelectorAllowlist: [...DEFAULT_CSS_SELECTOR_ALLOWLIST],
    exposureDuration: DEFAULT_EXPOSURE_DURATION,
    elementSelector: {
      enabled: resolved.enabled,
      shadowDomEnabled: resolved.shadowDomEnabled,
      maxShadowDomDepth: resolved.maxShadowDomDepth,
      autogeneratedIdPatterns: DEFAULT_AUTOGENERATED_ID_PATTERNS.map(source),
      unstableClassPatterns: DEFAULT_UNSTABLE_CLASS_PATTERNS.map(source),
    },
  };
};

/** Defer to the SDK's own clamping rather than restating the bounds here. */
const clampShadowDepth = (depth: number): number =>
  resolveSelectorConfig({ maxShadowDomDepth: depth }).maxShadowDomDepth;

/**
 * Pick the smallest set of selectors that covers every likely-interactive
 * element the current allowlist misses. Specific selectors are exhausted before
 * the broad catch-alls so the proposal reads as `[role="button" i]` rather than
 * `[tabindex]` whenever the DOM gives us that option.
 */
const allowlistAdditions = (missing: ElementRecord[]): AllowlistAddition[] => {
  const additions: AllowlistAddition[] = [];
  let uncovered = missing.filter((record) => record.interactiveReasons.length > 0);

  const tiers = [
    (selector: string) => !BROAD_INTERACTIVE_SELECTORS.includes(selector),
    (selector: string) => BROAD_INTERACTIVE_SELECTORS.includes(selector),
  ];

  for (const inTier of tiers) {
    for (;;) {
      const coverage = new Map<string, ElementRecord[]>();
      uncovered.forEach((record) =>
        record.interactiveReasons
          .filter(inTier)
          .forEach((selector) => coverage.set(selector, [...(coverage.get(selector) ?? []), record])),
      );
      if (coverage.size === 0) break;

      const [selector, covered] = Array.from(coverage).sort((a, b) => b[1].length - a[1].length)[0];
      const broad = BROAD_INTERACTIVE_SELECTORS.includes(selector);
      additions.push({
        selector,
        matchedElements: covered.length,
        broad,
        examples: covered.slice(0, 5).map((record) => record.selector),
        reason: broad
          ? 'Fallback. No semantic selector covers these elements, so this catch-all is the only way to reach them. Review the examples before adding it, it will also match elements this audit never saw.'
          : 'Covers likely-interactive elements that the current allowlist misses.',
      });

      const coveredSet = new Set(covered);
      uncovered = uncovered.filter((record) => !coveredSet.has(record));
    }
  }

  return additions;
};

const addedTo = (from: string[], to: string[]): string[] => to.filter((value) => !from.includes(value));

const listChange = (
  field: string,
  sdkDefault: string[],
  audited: string[],
  recommended: string[],
  reason: string,
): ListChange => {
  const added = addedTo(sdkDefault, recommended);
  const removed = addedTo(recommended, sdkDefault);
  return {
    field,
    kind: 'list',
    changed: added.length > 0 || removed.length > 0,
    harnessControlled: false,
    entryCount: { sdkDefault: sdkDefault.length, audited: audited.length, recommended: recommended.length },
    added,
    removed,
    reason,
  };
};

const scalarChange = (
  field: string,
  sdkDefault: number | boolean,
  audited: number | boolean,
  recommended: number | boolean,
  reason: string,
  harnessControlled = false,
): ScalarChange => ({
  field,
  kind: 'value',
  changed: sdkDefault !== recommended,
  harnessControlled,
  sdkDefault,
  audited,
  recommended,
  reason,
});

/**
 * Build the side-by-side view of SDK defaults, the settings this run used, and
 * the settings the evidence supports — so the diff can be reviewed before
 * anything is typed into a customer's remote config.
 */
const compareSettings = (
  audited: ConfigSnapshot,
  missing: ElementRecord[],
  records: ElementRecord[],
  suggestions: PatternSuggestion[],
): SettingsComparison => {
  const defaults = sdkDefaults();
  const additions = allowlistAdditions(missing);

  const shadowCrossings = Math.max(
    0,
    ...records.map((record) => record.selector.split(SHADOW_BOUNDARY_DELIMITER).length - 1),
  );
  const shadowDomEnabled = shadowCrossings > 0;

  const recommended: ConfigSnapshot = {
    cssSelectorAllowlist: [...audited.cssSelectorAllowlist, ...additions.map((addition) => addition.selector)],
    exposureDuration: audited.exposureDuration,
    elementSelector: {
      enabled: true,
      shadowDomEnabled,
      maxShadowDomDepth: shadowDomEnabled
        ? clampShadowDepth(shadowCrossings)
        : defaults.elementSelector.maxShadowDomDepth,
      autogeneratedIdPatterns: [
        ...audited.elementSelector.autogeneratedIdPatterns,
        ...suggestions.filter((entry) => entry.kind === 'autogeneratedId').map((entry) => entry.pattern),
      ],
      unstableClassPatterns: [
        ...audited.elementSelector.unstableClassPatterns,
        ...suggestions.filter((entry) => entry.kind === 'unstableClass').map((entry) => entry.pattern),
      ],
    },
  };

  const changes: ConfigChange[] = [
    listChange(
      'cssSelectorAllowlist',
      defaults.cssSelectorAllowlist,
      audited.cssSelectorAllowlist,
      recommended.cssSelectorAllowlist,
      additions.length
        ? 'The audit saw likely-interactive elements that no allowlist entry matches.'
        : 'Every likely-interactive element on this page is already covered.',
    ),
    scalarChange(
      'exposureDuration',
      defaults.exposureDuration,
      audited.exposureDuration,
      recommended.exposureDuration,
      'Carried over from the audited settings. The audit has no evidence for changing the dwell threshold.',
    ),
    scalarChange(
      'elementSelector.enabled',
      defaults.elementSelector.enabled,
      audited.elementSelector.enabled,
      recommended.elementSelector.enabled,
      'The v1 engine ships dormant. None of the selector settings below take effect until it is enabled.',
      true,
    ),
    scalarChange(
      'elementSelector.shadowDomEnabled',
      defaults.elementSelector.shadowDomEnabled,
      audited.elementSelector.shadowDomEnabled,
      recommended.elementSelector.shadowDomEnabled,
      shadowDomEnabled
        ? `Selectors on this page crossed up to ${shadowCrossings} shadow boundaries. Without piercing, those elements are not addressable.`
        : 'No selector on this page crossed a shadow boundary, so piercing stays off.',
      true,
    ),
    scalarChange(
      'elementSelector.maxShadowDomDepth',
      defaults.elementSelector.maxShadowDomDepth,
      audited.elementSelector.maxShadowDomDepth,
      recommended.elementSelector.maxShadowDomDepth,
      shadowDomEnabled
        ? 'Set to the deepest shadow nesting the audit actually observed.'
        : 'Left at the default because shadow piercing is not needed here.',
      true,
    ),
    listChange(
      'elementSelector.autogeneratedIdPatterns',
      defaults.elementSelector.autogeneratedIdPatterns,
      audited.elementSelector.autogeneratedIdPatterns,
      recommended.elementSelector.autogeneratedIdPatterns,
      'Patterns listed here replace the defaults rather than merging with them, so this is the full list to paste.',
    ),
    listChange(
      'elementSelector.unstableClassPatterns',
      defaults.elementSelector.unstableClassPatterns,
      audited.elementSelector.unstableClassPatterns,
      recommended.elementSelector.unstableClassPatterns,
      'Patterns listed here replace the defaults rather than merging with them, so this is the full list to paste.',
    ),
  ];

  const notes: string[] = [
    'Recommendations are built from what this page showed during this run. Elements that never rendered cannot be represented here.',
  ];
  if (additions.some((addition) => addition.broad)) {
    notes.push(
      'At least one allowlist addition is a broad catch-all. Confirm the examples are worth capturing before applying it.',
    );
  }
  const auditedCustomizations = (
    [
      ['cssSelectorAllowlist', defaults.cssSelectorAllowlist, audited.cssSelectorAllowlist],
      ['exposureDuration', defaults.exposureDuration, audited.exposureDuration],
      [
        'elementSelector.autogeneratedIdPatterns',
        defaults.elementSelector.autogeneratedIdPatterns,
        audited.elementSelector.autogeneratedIdPatterns,
      ],
      [
        'elementSelector.unstableClassPatterns',
        defaults.elementSelector.unstableClassPatterns,
        audited.elementSelector.unstableClassPatterns,
      ],
    ] as Array<[string, ConfigValue, ConfigValue]>
  )
    .filter(([, sdkDefault, value]) => JSON.stringify(sdkDefault) !== JSON.stringify(value))
    .map(([field]) => field);
  if (auditedCustomizations.length) {
    notes.push(
      `This run did not use stock SDK settings for ${auditedCustomizations.join(
        ', ',
      )}. The recommended column builds on the audited column, so review all three before applying.`,
    );
  }

  return {
    hasRecommendedChanges: changes.some((change) => change.changed),
    auditedMatchesSdkDefaults: auditedCustomizations.length === 0,
    auditedCustomizations,
    sdkDefaults: defaults,
    audited,
    recommended,
    changes,
    allowlistAdditions: additions,
    apply: {
      remoteConfigKey: ELEMENT_SELECTOR_REMOTE_CONFIG_KEY,
      remoteConfigPayload: recommended.elementSelector,
      sdkOptions: {
        cssSelectorAllowlist: recommended.cssSelectorAllowlist,
        exposureDuration: recommended.exposureDuration,
      },
    },
    notes,
  };
};

export const install = (options: AuditOptions = {}): void => {
  harness?.exposureTracker.unsubscribe();
  elementInstanceIds = new WeakMap<Element, number>();
  nextElementInstanceId = 1;

  const allowlist = options.allowlist?.length ? options.allowlist : [...DEFAULT_CSS_SELECTOR_ALLOWLIST];
  const elementSelector: ElementSelectorRemoteConfig = {
    enabled: true,
    shadowDomEnabled: true,
    maxShadowDomDepth: 10,
    ...options.elementSelector,
  };
  const exposureDuration = options.exposureDuration ?? DEFAULT_EXPOSURE_DURATION;
  const selectorConfig = resolveSelectorConfig(elementSelector);
  const engine = createSelectorEngine(selectorConfig);
  const extractor = new DataExtractor({});
  extractor.updateSelectorConfig(elementSelector);

  const mutationObservable = multicast(
    createMutationObservable(extractor.shadowGate).map((event) => ({
      event,
      timestamp: Date.now(),
      type: 'mutation' as const,
    })),
  );
  const exposureObservable = createExposureObservable(mutationObservable, allowlist, extractor.shadowGate);
  const scrollObservable = createScrollObservable();
  const exposed = new Set<string>();
  const allObservables = {
    [ObservablesEnum.MutationObservable]: mutationObservable,
    [ObservablesEnum.ExposureObservable]: exposureObservable,
    [ObservablesEnum.ScrollObservable]: scrollObservable,
  } as AllWindowObservables;
  const exposureTracker = trackExposure({
    allObservables,
    dataExtractor: extractor,
    exposureDuration,
    onExposure: (selector) => exposed.add(selector),
  });

  harness = {
    options: { allowlist, elementSelector, exposureDuration },
    engine,
    extractor,
    exposureTracker,
    exposed,
    lastSnapshotExposed: new Set(),
    scenarios: [],
  };
};

export const snapshot = (name: string): ScenarioRecord => {
  if (!harness) throw new Error('Install the exposure audit before taking a snapshot.');
  const activeHarness = harness;
  const elements = collectElements()
    .filter(
      (element) =>
        matchesAny(element, activeHarness.options.allowlist) || matchesAny(element, LIKELY_INTERACTIVE_SELECTORS),
    )
    .map((element) => describe(element, activeHarness));
  const newlyExposed = Array.from(activeHarness.exposed).filter(
    (selector) => !activeHarness.lastSnapshotExposed.has(selector),
  );
  const scenario: ScenarioRecord = {
    name,
    url: location.href,
    scrollX,
    scrollY,
    viewport: { width: innerWidth, height: innerHeight },
    newlyExposed,
    exposed: Array.from(activeHarness.exposed),
    elements,
  };
  activeHarness.scenarios.push(scenario);
  activeHarness.lastSnapshotExposed = new Set(activeHarness.exposed);
  return scenario;
};

export const report = (): AuditReport => {
  if (!harness) throw new Error('Install the exposure audit before creating a report.');
  const all = harness.scenarios.flatMap((scenario) => scenario.elements);
  const latestBySelector = new Map<string, ElementRecord>();
  all.forEach((record) => latestBySelector.set(record.selector, record));
  const records = Array.from(latestBySelector.values());
  const missingFromAllowlist = records.filter((record) => record.likelyInteractive && !record.allowlisted);
  const selectorProblems = records.filter((record) => record.matchCount !== 1 || !record.resolvesToTarget);
  const selectorsByInstance = new Map<number, { key: string; selectors: Set<string> }>();
  all.forEach((record) => {
    const group = selectorsByInstance.get(record.instanceId) ?? { key: record.key, selectors: new Set<string>() };
    group.selectors.add(record.selector);
    selectorsByInstance.set(record.instanceId, group);
  });
  const unstableSelectorGroups = Array.from(selectorsByInstance.values())
    .filter(({ selectors }) => selectors.size > 1)
    .map(({ key, selectors }) => ({ key, selectors: Array.from(selectors) }));
  const selectorConfig = resolveSelectorConfig(harness.options.elementSelector);
  const suggestions = patternSuggestions(harness.scenarios, selectorConfig);
  const likelyInteractive = records.filter((record) => record.likelyInteractive);
  const configuredIdPatterns =
    harness.options.elementSelector.autogeneratedIdPatterns ?? DEFAULT_AUTOGENERATED_ID_PATTERNS.map(source);
  const configuredClassPatterns =
    harness.options.elementSelector.unstableClassPatterns ?? DEFAULT_UNSTABLE_CLASS_PATTERNS.map(source);

  const audited: ConfigSnapshot = {
    cssSelectorAllowlist: harness.options.allowlist,
    exposureDuration: harness.options.exposureDuration,
    elementSelector: {
      enabled: selectorConfig.enabled,
      shadowDomEnabled: selectorConfig.shadowDomEnabled,
      maxShadowDomDepth: selectorConfig.maxShadowDomDepth,
      autogeneratedIdPatterns: configuredIdPatterns,
      unstableClassPatterns: configuredClassPatterns,
    },
  };
  const settings = compareSettings(audited, missingFromAllowlist, records, suggestions);

  return {
    url: location.href,
    title: document.title,
    generatedAt: new Date().toISOString(),
    settings,
    summary: {
      scenarios: harness.scenarios.length,
      likelyInteractive: likelyInteractive.length,
      allowlisted: likelyInteractive.filter((record) => record.allowlisted).length,
      missingFromAllowlist: missingFromAllowlist.length,
      exposed: harness.exposed.size,
      nonUniqueSelectors: selectorProblems.filter((record) => record.matchCount !== 1).length,
      selectorsThatMissTarget: selectorProblems.filter((record) => !record.resolvesToTarget).length,
      unstableSelectorGroups: unstableSelectorGroups.length,
      patternSuggestions: suggestions.length,
      recommendedChanges: settings.changes.filter((change) => change.changed).length,
    },
    missingFromAllowlist,
    selectorProblems,
    unstableSelectorGroups,
    patternSuggestions: suggestions,
    scenarios: harness.scenarios,
  };
};
