import { DEFAULT_CSS_SELECTOR_ALLOWLIST, DEFAULT_EXPOSURE_DURATION, multicast } from '@amplitude/analytics-core';
import {
  createSelectorEngine,
  DEFAULT_AUTOGENERATED_ID_PATTERNS,
  DEFAULT_UNSTABLE_CLASS_PATTERNS,
  resolveSelector,
  resolveSelectorConfig,
  SHADOW_BOUNDARY_DELIMITER,
  type ElementSelectorRemoteConfig,
} from '@amplitude/element-selector';
import { ObservablesEnum, type AllWindowObservables } from '../src/autocapture-plugin';
import { trackExposure } from '../src/autocapture/track-exposure';
import { DataExtractor } from '../src/data-extractor';
import { createExposureObservable, createMutationObservable, createScrollObservable } from '../src/observables';

declare global {
  interface Window {
    AmplitudeExposureAudit: {
      install: typeof install;
      snapshot: typeof snapshot;
      report: typeof report;
    };
  }
}

const LIKELY_INTERACTIVE_SELECTORS = [
  'a[href]',
  'button',
  'input:not([type="hidden"])',
  'select',
  'textarea',
  'label',
  'summary',
  '[contenteditable="true" i]',
  '[onclick]',
  '[role="button" i]',
  '[role="checkbox" i]',
  '[role="combobox" i]',
  '[role="link" i]',
  '[role="menuitem" i]',
  '[role="option" i]',
  '[role="radio" i]',
  '[role="slider" i]',
  '[role="switch" i]',
  '[role="tab" i]',
  '[tabindex]:not([tabindex="-1"])',
];

type AuditOptions = {
  allowlist?: string[];
  elementSelector?: ElementSelectorRemoteConfig;
  exposureDuration?: number;
};

type ElementRecord = {
  instanceId: number;
  key: string;
  tag: string;
  text: string;
  role: string | null;
  id: string | null;
  classes: string[];
  allowlisted: boolean;
  likelyInteractive: boolean;
  selector: string;
  matchCount: number;
  resolvesToTarget: boolean;
};

type ScenarioRecord = {
  name: string;
  url: string;
  scrollX: number;
  scrollY: number;
  viewport: { width: number; height: number };
  newlyExposed: string[];
  exposed: string[];
  elements: ElementRecord[];
};

type PatternSuggestion = {
  kind: 'autogeneratedId' | 'unstableClass';
  pattern: string;
  evidence: string[];
  reason: string;
};

type AuditReport = {
  url: string;
  title: string;
  generatedAt: string;
  configuration: {
    allowlist: string[];
    exposureDuration: number;
    elementSelector: {
      enabled: boolean;
      shadowDomEnabled: boolean;
      maxShadowDomDepth: number;
      autogeneratedIdPatterns: string[];
      unstableClassPatterns: string[];
    };
  };
  summary: {
    scenarios: number;
    likelyInteractive: number;
    allowlisted: number;
    missingFromAllowlist: number;
    exposed: number;
    nonUniqueSelectors: number;
    selectorsThatMissTarget: number;
    unstableSelectorGroups: number;
    patternSuggestions: number;
  };
  missingFromAllowlist: ElementRecord[];
  selectorProblems: ElementRecord[];
  unstableSelectorGroups: Array<{ key: string; selectors: string[] }>;
  patternSuggestions: PatternSuggestion[];
  scenarios: ScenarioRecord[];
};

type Harness = {
  options: Required<Pick<AuditOptions, 'allowlist' | 'exposureDuration'>> & {
    elementSelector: ElementSelectorRemoteConfig;
  };
  engine: ReturnType<typeof createSelectorEngine>;
  extractor: DataExtractor;
  exposureTracker: ReturnType<typeof trackExposure>;
  exposed: Set<string>;
  lastSnapshotExposed: Set<string>;
  scenarios: ScenarioRecord[];
};

let harness: Harness | undefined;
let nextElementInstanceId = 1;
let elementInstanceIds = new WeakMap<Element, number>();

const instanceIdOf = (element: Element): number => {
  const existing = elementInstanceIds.get(element);
  if (existing) return existing;
  const next = nextElementInstanceId;
  nextElementInstanceId += 1;
  elementInstanceIds.set(element, next);
  return next;
};

const textOf = (element: Element): string =>
  (element.getAttribute('aria-label') || element.textContent || '').replace(/\s+/g, ' ').trim().slice(0, 120);

const elementKey = (element: Element): string =>
  [
    element.tagName.toLowerCase(),
    element.getAttribute('role') || '',
    element.getAttribute('name') || '',
    element.getAttribute('aria-label') || '',
    textOf(element),
  ].join('|');

const matchesAny = (element: Element, selectors: string[]): boolean =>
  selectors.some((selector) => {
    try {
      return element.matches(selector);
    } catch {
      return false;
    }
  });

const collectElements = (root: Document | ShadowRoot = document): Element[] => {
  const elements: Element[] = [];
  root.querySelectorAll('*').forEach((element) => {
    if (element.closest('[data-amplitude-exposure-audit]')) return;
    elements.push(element);
    if (element.shadowRoot) {
      elements.push(...collectElements(element.shadowRoot));
    }
  });
  return elements;
};

const selectorMatchCount = (selector: string): number => {
  const segments = selector.split(SHADOW_BOUNDARY_DELIMITER).map((segment) => segment.trim());
  let scope: ParentNode | null = document;
  for (let index = 0; index < segments.length; index += 1) {
    if (!scope) return 0;
    const segment = segments[index];
    if (segment.startsWith(':scope >')) {
      const steps = segment
        .slice(':scope >'.length)
        .split('>')
        .map((step) => step.trim());
      let candidates = Array.from(scope.children);
      let found: Element[] = [];
      for (const step of steps) {
        found = candidates.filter((candidate) => candidate.matches(step));
        if (found.length !== 1) return found.length;
        candidates = Array.from(found[0].children);
      }
      if (index === segments.length - 1) return found.length;
      scope = found[0]?.shadowRoot ?? null;
      continue;
    }
    let matches: Element[];
    try {
      matches = Array.from(scope.querySelectorAll(segment));
    } catch {
      return 0;
    }
    if (index === segments.length - 1) return matches.length;
    if (matches.length !== 1) return matches.length;
    scope = matches[0].shadowRoot;
  }
  return 0;
};

const describe = (element: Element, activeHarness: Harness): ElementRecord => {
  const selector = activeHarness.engine.generate(element);
  const resolved = resolveSelector(document, selector);
  return {
    instanceId: instanceIdOf(element),
    key: elementKey(element),
    tag: element.tagName.toLowerCase(),
    text: textOf(element),
    role: element.getAttribute('role'),
    id: element.id || null,
    classes: Array.from(element.classList),
    allowlisted: matchesAny(element, activeHarness.options.allowlist),
    likelyInteractive: matchesAny(element, LIKELY_INTERACTIVE_SELECTORS),
    selector,
    matchCount: selectorMatchCount(selector),
    resolvesToTarget: resolved === element,
  };
};

const source = (pattern: RegExp): string => pattern.source;

const commonPrefix = (values: string[]): string => {
  if (values.length === 0) return '';
  let prefix = values[0];
  for (const value of values.slice(1)) {
    while (prefix && !value.startsWith(prefix)) prefix = prefix.slice(0, -1);
  }
  return prefix;
};

const escapeRegex = (value: string): string => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

const looksGenerated = (value: string): boolean =>
  /[a-f0-9]{8}-[a-f0-9-]{20,}/i.test(value) ||
  /(?:^|[-_])[a-f0-9]{8,}(?:[-_]|$)/i.test(value) ||
  /(?:^|[-_])(?=[a-z0-9]{10,}(?:[-_]|$))(?=[a-z0-9]*[a-z])(?=[a-z0-9]*\d)[a-z0-9]+(?:[-_]|$)/i.test(value) ||
  /__[A-Za-z0-9_]+__[A-Za-z0-9]{5,}$/.test(value);

const generatedPrefix = (value: string): string => {
  const token = value.match(
    /(?:^|[-_])(?:[a-f0-9]{8,}|(?=[a-z0-9]{10,}(?:[-_]|$))(?=[a-z0-9]*[a-z])(?=[a-z0-9]*\d)[a-z0-9]+)(?=[-_]|$)/i,
  );
  if (!token || token.index === undefined) return '';
  const delimiterLength = token[0].startsWith('-') || token[0].startsWith('_') ? 1 : 0;
  return value.slice(0, token.index + delimiterLength);
};

const patternSuggestions = (scenarios: ScenarioRecord[], config: ReturnType<typeof resolveSelectorConfig>) => {
  const suggestions: PatternSuggestion[] = [];
  const all = scenarios.flatMap((scenario) => scenario.elements);
  const ids = Array.from(
    new Set(all.map((element) => element.id).filter((id): id is string => typeof id === 'string' && id.length > 0)),
  );
  const uncoveredIds = ids.filter(
    (id) => looksGenerated(id) && !config.autogeneratedIdPatterns.some((pattern) => Boolean(pattern.test(id))),
  );

  const idGroups = new Map<string, string[]>();
  uncoveredIds.forEach((id) => {
    const prefix = generatedPrefix(id);
    if (!prefix) return;
    idGroups.set(prefix, [...(idGroups.get(prefix) ?? []), id]);
  });
  idGroups.forEach((evidence, prefix) => {
    if (evidence.length < 2) return;
    suggestions.push({
      kind: 'autogeneratedId',
      pattern: `^${escapeRegex(prefix)}`,
      evidence: evidence.slice(0, 10),
      reason: 'Multiple generated-looking IDs share this prefix and are not covered by the active patterns.',
    });
  });

  const recordsByInstance = new Map<number, ElementRecord[]>();
  all.forEach((record) =>
    recordsByInstance.set(record.instanceId, [...(recordsByInstance.get(record.instanceId) ?? []), record]),
  );
  recordsByInstance.forEach((records) => {
    const variants = Array.from(
      new Set(records.map((record) => record.id).filter((id): id is string => typeof id === 'string' && id.length > 0)),
    );
    if (
      variants.length < 2 ||
      variants.every((id) => config.autogeneratedIdPatterns.some((pattern) => Boolean(pattern.test(id))))
    ) {
      return;
    }
    const prefix = commonPrefix(variants).replace(/[A-Za-z0-9]+$/, '');
    if (prefix.length < 3) return;
    suggestions.push({
      kind: 'autogeneratedId',
      pattern: `^${escapeRegex(prefix)}`,
      evidence: variants.slice(0, 10),
      reason: 'The same semantic component produced different IDs between scenarios.',
    });
  });

  const classesByKey = new Map<string, string[]>();
  recordsByInstance.forEach((records) => {
    const classSets = Array.from(new Set(records.map((record) => [...record.classes].sort().join(' '))));
    if (classSets.length < 2) return;
    const occurrenceCount = new Map<string, number>();
    records.forEach((record) => {
      new Set(record.classes).forEach((className) =>
        occurrenceCount.set(className, (occurrenceCount.get(className) ?? 0) + 1),
      );
    });
    const changingClasses = Array.from(occurrenceCount)
      .filter(([, count]) => count < records.length)
      .map(([className]) => className);
    if (changingClasses.length) classesByKey.set(records[0].key, changingClasses);
  });
  classesByKey.forEach((classes) => {
    const uncovered = classes.filter(
      (className) =>
        looksGenerated(className) && !config.unstableClassPatterns.some((pattern) => Boolean(pattern.test(className))),
    );
    const prefix = commonPrefix(uncovered).replace(/[A-Za-z0-9]+$/, '');
    if (uncovered.length < 2 || prefix.length < 3) return;
    suggestions.push({
      kind: 'unstableClass',
      pattern: `^${escapeRegex(prefix)}`,
      evidence: uncovered.slice(0, 10),
      reason:
        'Generated-looking class variants appear on the same semantic component. The current v1 selector does not emit classes, but this pattern protects class-aware consumers.',
    });
  });

  return suggestions.filter(
    (suggestion, index) =>
      suggestions.findIndex(
        (candidate) => candidate.kind === suggestion.kind && candidate.pattern === suggestion.pattern,
      ) === index,
  );
};

export const install = (options: AuditOptions = {}): void => {
  harness?.exposureTracker.unsubscribe();
  elementInstanceIds = new WeakMap<Element, number>();
  nextElementInstanceId = 1;

  const allowlist = options.allowlist?.length ? options.allowlist : [...DEFAULT_CSS_SELECTOR_ALLOWLIST];
  const elementSelector: ElementSelectorRemoteConfig = {
    enabled: true,
    shadowDomEnabled: true,
    maxShadowDomDepth: 10,
    ...options.elementSelector,
  };
  const exposureDuration = options.exposureDuration ?? DEFAULT_EXPOSURE_DURATION;
  const selectorConfig = resolveSelectorConfig(elementSelector);
  const engine = createSelectorEngine(selectorConfig);
  const extractor = new DataExtractor({});
  extractor.updateSelectorConfig(elementSelector);

  const mutationObservable = multicast(
    createMutationObservable(extractor.shadowGate).map((event) => ({
      event,
      timestamp: Date.now(),
      type: 'mutation' as const,
    })),
  );
  const exposureObservable = createExposureObservable(mutationObservable, allowlist, extractor.shadowGate);
  const scrollObservable = createScrollObservable();
  const exposed = new Set<string>();
  const allObservables = {
    [ObservablesEnum.MutationObservable]: mutationObservable,
    [ObservablesEnum.ExposureObservable]: exposureObservable,
    [ObservablesEnum.ScrollObservable]: scrollObservable,
  } as AllWindowObservables;
  const exposureTracker = trackExposure({
    allObservables,
    dataExtractor: extractor,
    exposureDuration,
    onExposure: (selector) => exposed.add(selector),
  });

  harness = {
    options: { allowlist, elementSelector, exposureDuration },
    engine,
    extractor,
    exposureTracker,
    exposed,
    lastSnapshotExposed: new Set(),
    scenarios: [],
  };
};

export const snapshot = (name: string): ScenarioRecord => {
  if (!harness) throw new Error('Install the exposure audit before taking a snapshot.');
  const activeHarness = harness;
  const elements = collectElements()
    .filter(
      (element) =>
        matchesAny(element, activeHarness.options.allowlist) || matchesAny(element, LIKELY_INTERACTIVE_SELECTORS),
    )
    .map((element) => describe(element, activeHarness));
  const newlyExposed = Array.from(activeHarness.exposed).filter(
    (selector) => !activeHarness.lastSnapshotExposed.has(selector),
  );
  const scenario: ScenarioRecord = {
    name,
    url: location.href,
    scrollX,
    scrollY,
    viewport: { width: innerWidth, height: innerHeight },
    newlyExposed,
    exposed: Array.from(activeHarness.exposed),
    elements,
  };
  activeHarness.scenarios.push(scenario);
  activeHarness.lastSnapshotExposed = new Set(activeHarness.exposed);
  return scenario;
};

export const report = (): AuditReport => {
  if (!harness) throw new Error('Install the exposure audit before creating a report.');
  const all = harness.scenarios.flatMap((scenario) => scenario.elements);
  const latestBySelector = new Map<string, ElementRecord>();
  all.forEach((record) => latestBySelector.set(record.selector, record));
  const records = Array.from(latestBySelector.values());
  const missingFromAllowlist = records.filter((record) => record.likelyInteractive && !record.allowlisted);
  const selectorProblems = records.filter((record) => record.matchCount !== 1 || !record.resolvesToTarget);
  const selectorsByInstance = new Map<number, { key: string; selectors: Set<string> }>();
  all.forEach((record) => {
    const group = selectorsByInstance.get(record.instanceId) ?? { key: record.key, selectors: new Set<string>() };
    group.selectors.add(record.selector);
    selectorsByInstance.set(record.instanceId, group);
  });
  const unstableSelectorGroups = Array.from(selectorsByInstance.values())
    .filter(({ selectors }) => selectors.size > 1)
    .map(({ key, selectors }) => ({ key, selectors: Array.from(selectors) }));
  const selectorConfig = resolveSelectorConfig(harness.options.elementSelector);
  const suggestions = patternSuggestions(harness.scenarios, selectorConfig);
  const likelyInteractive = records.filter((record) => record.likelyInteractive);
  const configuredIdPatterns =
    harness.options.elementSelector.autogeneratedIdPatterns ?? DEFAULT_AUTOGENERATED_ID_PATTERNS.map(source);
  const configuredClassPatterns =
    harness.options.elementSelector.unstableClassPatterns ?? DEFAULT_UNSTABLE_CLASS_PATTERNS.map(source);

  return {
    url: location.href,
    title: document.title,
    generatedAt: new Date().toISOString(),
    configuration: {
      allowlist: harness.options.allowlist,
      exposureDuration: harness.options.exposureDuration,
      elementSelector: {
        enabled: selectorConfig.enabled,
        shadowDomEnabled: selectorConfig.shadowDomEnabled,
        maxShadowDomDepth: selectorConfig.maxShadowDomDepth,
        autogeneratedIdPatterns: configuredIdPatterns,
        unstableClassPatterns: configuredClassPatterns,
      },
    },
    summary: {
      scenarios: harness.scenarios.length,
      likelyInteractive: likelyInteractive.length,
      allowlisted: likelyInteractive.filter((record) => record.allowlisted).length,
      missingFromAllowlist: missingFromAllowlist.length,
      exposed: harness.exposed.size,
      nonUniqueSelectors: selectorProblems.filter((record) => record.matchCount !== 1).length,
      selectorsThatMissTarget: selectorProblems.filter((record) => !record.resolvesToTarget).length,
      unstableSelectorGroups: unstableSelectorGroups.length,
      patternSuggestions: suggestions.length,
    },
    missingFromAllowlist,
    selectorProblems,
    unstableSelectorGroups,
    patternSuggestions: suggestions,
    scenarios: harness.scenarios,
  };
};
