import { test, expect } from '@playwright/test';

/**
 * Two SDK instances on one page, with element-selector remote config enabled for one API key and
 * disabled for the other. Selector state used to live in module-level singletons, so whichever
 * config was delivered last decided the selectors for every instance on the page; and a delivery
 * was handed to every subscriber by reference, so the browser SDK's in-place normalization of
 * `{ enabled: true }` stripped the flag the selector engine keys off before caching it.
 *
 * The page (`test-server/element-selector-multi-instance.html`) runs the checks itself and reports
 * a verdict, so the same validation is available by hand with `pnpm dev`. This spec drives it and
 * pulls out the per-check cells so a failure names what diverged.
 */
test.describe('autocapture element selector across SDK instances', () => {
  test('keeps enabled and disabled instances on their own selectors', async ({ page }) => {
    const pageErrors: string[] = [];
    page.on('pageerror', (error) => pageErrors.push(error.message));

    await page.goto('/element-selector-multi-instance.html');
    await expect(page.locator('#status')).not.toHaveText('running', { timeout: 30_000 });

    const engineOn = await page.locator('#check-engine-on-actual').textContent();
    const engineOff = await page.locator('#check-engine-off-actual').textContent();

    // The enabled instance treats the probe id (`amp-probe-12345`) as autogenerated and falls back
    // to structure; the disabled instance stays on the legacy `tag#id` walker.
    expect(engineOn).not.toContain('amp-probe-12345');
    expect(engineOff).toBe('button#amp-probe-12345');

    // Each instance's cached config must still carry the boolean it was delivered.
    await expect(page.locator('#check-cache-a-actual')).toHaveText('{"enabled":true}');
    await expect(page.locator('#check-cache-b-actual')).toHaveText('{"enabled":false}');

    await expect(page.locator('#status')).toHaveText('pass');
    expect(pageErrors).toEqual([]);
  });
});
