import { DEFAULT_AUTOGENERATED_ID_PATTERNS, compile, isStableId } from '../../src/patterns/autogenerated-ids';

describe('DEFAULT_AUTOGENERATED_ID_PATTERNS', () => {
  // Real-world examples drawn from each pattern's target convention. Updating
  // this table requires updating the corresponding regex (and vice versa).
  const matchCases: Array<{ id: string; reason: string }> = [
    { id: ':r0:', reason: 'React useId — minimum form' },
    { id: ':r5:', reason: 'React useId — common form' },
    { id: ':rk:', reason: 'React useId — alphanumeric counter' },
    { id: 'radix-:r3:', reason: 'Radix UI primitive id' },
    { id: 'radix-A1B2C3', reason: 'Radix UI primitive without React useId suffix' },
    { id: 'headlessui-menu-button-:r5:', reason: 'Headless UI button id' },
    { id: 'mui-12345', reason: 'MUI internal id prefix' },
    { id: 'a9b8c7d6e5f4321b3', reason: 'Hex-only 17-char string (UUID-ish / build hash)' },
    { id: 'session-1700000000', reason: 'Trailing 10-digit timestamp' },
    { id: 'row-20250515', reason: 'Trailing 8-digit date counter' },
    { id: 'product-2134', reason: 'Four consecutive digits in mid-string (ContentSquare heuristic)' },
    { id: 'swiper-wrapper-2e110fa710fd7e41039', reason: 'Real Swiper wrapper id; trips on the 41039 substring' },
  ];

  const nonMatchCases: Array<{ id: string; reason: string }> = [
    { id: 'checkout-button', reason: 'Plain semantic id' },
    { id: 'main', reason: 'Single-word id' },
    { id: 'search-input', reason: 'Plain hyphenated id' },
    { id: 'product-A2', reason: 'Mixed alphanumeric with no consecutive 4-digit run' },
    { id: 'row-A1B', reason: 'Mixed alphanumeric short suffix' },
    { id: 'login-form', reason: 'Plain compound id' },
    { id: 'header-q4', reason: 'Quarter suffix without 4+ digits' },
    { id: 'abc', reason: 'Short alphanumeric — does not meet 16-char hex threshold' },
  ];

  matchCases.forEach(({ id, reason }) => {
    it(`flags "${id}" as autogenerated (${reason})`, () => {
      const matched = DEFAULT_AUTOGENERATED_ID_PATTERNS.some((p) => p.test(id));
      expect(matched).toBe(true);
    });
  });

  nonMatchCases.forEach(({ id, reason }) => {
    it(`does not flag "${id}" (${reason})`, () => {
      const matched = DEFAULT_AUTOGENERATED_ID_PATTERNS.some((p) => p.test(id));
      expect(matched).toBe(false);
    });
  });
});

describe('compile()', () => {
  it('returns an empty array for an empty input list', () => {
    expect(compile([])).toEqual([]);
  });

  it('compiles valid regex strings to RegExp instances', () => {
    const result = compile(['^foo-', '^bar-\\d+$']);
    expect(result).toHaveLength(2);
    expect(result[0]).toBeInstanceOf(RegExp);
    expect(result[0].test('foo-baz')).toBe(true);
    expect(result[0].test('not-foo')).toBe(false);
  });

  it('skips invalid regex strings silently rather than throwing', () => {
    const result = compile(['^valid$', '[unclosed-bracket', '^another-valid$']);
    expect(result).toHaveLength(2);
    expect(result[0].test('valid')).toBe(true);
    expect(result[1].test('another-valid')).toBe(true);
  });

  it('emits a warn through the provided logger for each invalid pattern', () => {
    const logger = {
      log: jest.fn(),
      warn: jest.fn(),
      error: jest.fn(),
      debug: jest.fn(),
      disable: jest.fn(),
      enable: jest.fn(),
    };
    compile(['^valid$', '[unclosed', '(also-bad'], logger);
    expect(logger.warn).toHaveBeenCalledTimes(2);
    expect(logger.warn).toHaveBeenCalledWith(expect.stringContaining('[unclosed'));
    expect(logger.warn).toHaveBeenCalledWith(expect.stringContaining('(also-bad'));
  });

  it('does not invoke the logger when no patterns are invalid', () => {
    const logger = {
      log: jest.fn(),
      warn: jest.fn(),
      error: jest.fn(),
      debug: jest.fn(),
      disable: jest.fn(),
      enable: jest.fn(),
    };
    compile(['^valid$', '^also-valid$'], logger);
    expect(logger.warn).not.toHaveBeenCalled();
  });
});

describe('isStableId()', () => {
  const patterns = [/^foo-/, /\d{4,}/];

  it('returns false for null id', () => {
    expect(isStableId(null, patterns)).toBe(false);
  });

  it('returns false for undefined id', () => {
    expect(isStableId(undefined, patterns)).toBe(false);
  });

  it('returns false for empty-string id', () => {
    expect(isStableId('', patterns)).toBe(false);
  });

  it('returns true for an id that matches no pattern', () => {
    expect(isStableId('checkout-button', patterns)).toBe(true);
  });

  it('returns false for an id that matches the prefix pattern', () => {
    expect(isStableId('foo-bar', patterns)).toBe(false);
  });

  it('returns false for an id that matches the substring pattern', () => {
    expect(isStableId('product-2134', patterns)).toBe(false);
  });

  it('returns true when given no patterns', () => {
    expect(isStableId('anything', [])).toBe(true);
  });
});
