/* eslint-disable @typescript-eslint/unbound-method */
export type {
  AmplitudeReturn,
  BaseEvent,
  EventOptions,
  BrowserClient,
  AttributionOptions,
  AutocaptureOptions,
  BrowserOptions,
  BrowserConfig,
  IConfig,
  Event,
  IdentifyEvent,
  GroupIdentifyEvent,
  IIdentify,
  IRevenue,
  ILogger,
  Plugin,
  BeforePlugin,
  EnrichmentPlugin,
  DestinationPlugin,
  Result,
  ServerZoneType,
  IdentityStorageType,
  Storage,
  TransportType,
  Messenger,
  ElementInteractionsOptions,
  ActionType,
  Campaign,
  ClickIdParameters,
  ReferrerParameters,
  UTMParameters,
  ValidPropertyType,
  ExcludeInternalReferrersOptions,
} from '@amplitude/analytics-core';
export {
  IdentifyOperation,
  SpecialEventType,
  RevenueProperty,
  LogLevel,
  ServerZone,
  OfflineDisabled,
  DEFAULT_CSS_SELECTOR_ALLOWLIST,
  DEFAULT_DATA_ATTRIBUTE_PREFIX,
  DEFAULT_ACTION_CLICK_ALLOWLIST,
  EXCLUDE_INTERNAL_REFERRERS_CONDITIONS,
} from '@amplitude/analytics-core';
