/**
 * @jest-environment jsdom
 */
import { getStableId } from '../../src/helpers/get-stable-id';
import { ResolvedSelectorConfig } from '../../src/types';

const baseConfig: ResolvedSelectorConfig = {
  enabled: true,
  explicitTrackingAttribute: 'data-amp-track-id',
  autogeneratedIdPatterns: [/^:r[0-9a-z]+:$/, /\d{4,}/],
  unstableClassPatterns: [],
  maxAncestorWalkDepth: undefined,
  shadowDomEnabled: false,
  maxShadowDomDepth: 1,
};

function makeElement(attrs: Record<string, string>): Element {
  const el = document.createElement('div');
  Object.entries(attrs).forEach(([key, value]) => {
    el.setAttribute(key, value);
  });
  return el;
}

describe('getStableId()', () => {
  describe('suppression via empty tracking attribute', () => {
    it('returns null when explicit-tracking attribute is set to empty string, even with a stable id', () => {
      const el = makeElement({
        id: 'checkout-button',
        'data-amp-track-id': '',
      });
      expect(getStableId(el, baseConfig)).toBeNull();
    });

    it('returns null when empty tracking attribute combines with an autogenerated id', () => {
      const el = makeElement({
        id: ':r5:',
        'data-amp-track-id': '',
      });
      expect(getStableId(el, baseConfig)).toBeNull();
    });

    it('does NOT suppress when tracking attribute is set to a non-empty value', () => {
      // Non-empty tracking attribute is a separate signal (handled by the
      // explicitTrackingAttribute strategy upstream); it doesn't suppress the id.
      const el = makeElement({
        id: 'checkout-button',
        'data-amp-track-id': 'some-label',
      });
      expect(getStableId(el, baseConfig)).toBe('checkout-button');
    });

    it('does NOT suppress when tracking attribute is absent', () => {
      const el = makeElement({ id: 'checkout-button' });
      expect(getStableId(el, baseConfig)).toBe('checkout-button');
    });
  });

  describe('id presence', () => {
    it('returns null when the element has no id attribute', () => {
      const el = makeElement({ class: 'something' });
      expect(getStableId(el, baseConfig)).toBeNull();
    });

    it('returns null when the id attribute is present but empty', () => {
      const el = makeElement({ id: '' });
      expect(getStableId(el, baseConfig)).toBeNull();
    });
  });

  describe('autogenerated-pattern filter', () => {
    it('returns null for a React useId-style id', () => {
      const el = makeElement({ id: ':r5:' });
      expect(getStableId(el, baseConfig)).toBeNull();
    });

    it('returns null for an id with a 4+ consecutive digit run', () => {
      const el = makeElement({ id: 'product-2134' });
      expect(getStableId(el, baseConfig)).toBeNull();
    });

    it('returns the id when it matches no autogenerated pattern', () => {
      const el = makeElement({ id: 'checkout-button' });
      expect(getStableId(el, baseConfig)).toBe('checkout-button');
    });
  });

  describe('honors a non-default explicit-tracking attribute name', () => {
    it('treats empty value on the custom attribute name as a suppression signal', () => {
      const cfg = { ...baseConfig, explicitTrackingAttribute: 'data-track' };
      const el = makeElement({
        id: 'checkout-button',
        'data-track': '',
      });
      expect(getStableId(el, cfg)).toBeNull();
    });
  });
});
