/**
 * @jest-environment jsdom
 */
import { fallbackCssPath } from '../src/fallback-css-path';
import { ResolvedSelectorConfig } from '../src/types';

const baseConfig: ResolvedSelectorConfig = {
  enabled: true,
  explicitTrackingAttribute: 'data-amp-track-id',
  autogeneratedIdPatterns: [/^:r[0-9a-z]+:$/, /\d{4,}/],
  unstableClassPatterns: [],
  maxAncestorWalkDepth: undefined,
  shadowDomEnabled: false,
  maxShadowDomDepth: 1,
};

function setBody(html: string): void {
  document.body.innerHTML = html;
}

describe('fallbackCssPath', () => {
  afterEach(() => {
    document.body.innerHTML = '';
  });

  describe('anchor termination on stable id', () => {
    it('terminates the walk at the nearest ancestor with a stable id', () => {
      setBody(`
        <section id="hero">
          <div>
            <button>x</button>
          </div>
        </section>
      `);
      const target = document.querySelector('button') as Element;
      expect(fallbackCssPath(target, baseConfig)).toBe('section#hero > div:nth-of-type(1) > button:nth-of-type(1)');
    });

    it('uses the target itself as anchor when its id is stable', () => {
      setBody(`<section><button id="cta-btn">x</button></section>`);
      const target = document.querySelector('button') as Element;
      expect(fallbackCssPath(target, baseConfig)).toBe('button#cta-btn');
    });
  });

  describe('autogenerated-id filtering', () => {
    it('walks past a React-style autogen id on the target', () => {
      setBody(`
        <section id="hero">
          <button id=":r5:">x</button>
        </section>
      `);
      const target = document.querySelector('button') as Element;
      expect(fallbackCssPath(target, baseConfig)).toBe('section#hero > button:nth-of-type(1)');
    });

    it('walks past a 4-digit-suffixed id', () => {
      setBody(`
        <section id="hero">
          <button id="row-9999">x</button>
        </section>
      `);
      const target = document.querySelector('button') as Element;
      expect(fallbackCssPath(target, baseConfig)).toBe('section#hero > button:nth-of-type(1)');
    });
  });

  describe('explicit-tracking-attribute suppression signal', () => {
    it('treats an empty value on the attribute as "ignore this id"', () => {
      // `data-amp-track-id=""` is the suppression signal — even though the id
      // would otherwise be usable, the fallback walks past it.
      setBody(`
        <section id="hero">
          <button id="cta-btn" data-amp-track-id="">x</button>
        </section>
      `);
      const target = document.querySelector('button') as Element;
      expect(fallbackCssPath(target, baseConfig)).toBe('section#hero > button:nth-of-type(1)');
    });
  });

  describe('nth-of-type sibling disambiguation', () => {
    it('produces position-stable selectors among same-tag siblings', () => {
      setBody(`
        <ul id="menu">
          <li><a>a</a></li>
          <li><a>b</a></li>
          <li><a>c</a></li>
        </ul>
      `);
      const target = document.querySelectorAll('li')[2] as Element;
      expect(fallbackCssPath(target, baseConfig)).toBe('ul#menu > li:nth-of-type(3)');
    });

    it('only counts same-tag siblings (not all siblings)', () => {
      setBody(`
        <div id="container">
          <span>a</span>
          <p>b</p>
          <span>c</span>
          <p>d</p>
        </div>
      `);
      const targetP = document.querySelectorAll('p')[1] as Element;
      // 2nd <p>, even though it's the 4th child overall.
      expect(fallbackCssPath(targetP, baseConfig)).toBe('div#container > p:nth-of-type(2)');
    });
  });

  describe('walk to document root when no id is available', () => {
    it('rooted at html when no stable id is found on the walk', () => {
      setBody(`<div><button>x</button></div>`);
      const target = document.querySelector('button') as Element;
      // body has no id, html has no id, walk all the way up. The first segment
      // (the document element) is just "html" since it has no parent.
      const result = fallbackCssPath(target, baseConfig);
      expect(result).toBe('html > body:nth-of-type(1) > div:nth-of-type(1) > button:nth-of-type(1)');
    });
  });

  describe('maxAncestorWalkDepth', () => {
    it('stops walking once the depth limit is reached', () => {
      setBody(`
        <section id="hero">
          <div>
            <div>
              <button>x</button>
            </div>
          </div>
        </section>
      `);
      const target = document.querySelector('button') as Element;
      const limited: ResolvedSelectorConfig = { ...baseConfig, maxAncestorWalkDepth: 2 };
      // Depth limit cuts off the walk before reaching <section id="hero">.
      // Result is rooted at whatever the deepest reached element is.
      const result = fallbackCssPath(target, limited);
      expect(result).toBe('div:nth-of-type(1) > div:nth-of-type(1) > button:nth-of-type(1)');
    });
  });

  describe('produces selectors that resolve to the original target', () => {
    it('round-trips correctly under querySelector for the standard nested case', () => {
      setBody(`
        <section id="hero">
          <div>
            <button>x</button>
          </div>
        </section>
      `);
      const target = document.querySelector('button') as Element;
      const selector = fallbackCssPath(target, baseConfig);
      expect(document.querySelector(selector)).toBe(target);
    });
  });

  describe('ambiguous id anchors', () => {
    it('skips a duplicate id and emits a selector that resolves to the target', () => {
      setBody(`
        <section>
          <div id="dupe"><button>a</button></div>
          <div id="dupe"><button>b</button></div>
        </section>
      `);
      const target = document.querySelectorAll('button')[1] as Element;
      const selector = fallbackCssPath(target, baseConfig);

      expect(selector).not.toContain('#dupe');
      expect(selector).toBe(
        'html > body:nth-of-type(1) > section:nth-of-type(1) > div:nth-of-type(2) > button:nth-of-type(1)',
      );
      expect(document.querySelector(selector)).toBe(target);
    });

    it('still uses a unique ancestor id after skipping a duplicate id', () => {
      setBody(`
        <section id="hero">
          <div id="dupe"><button>a</button></div>
          <div id="dupe"><button>b</button></div>
        </section>
      `);
      const target = document.querySelectorAll('button')[1] as Element;
      const selector = fallbackCssPath(target, baseConfig);

      expect(selector).toBe('section#hero > div:nth-of-type(2) > button:nth-of-type(1)');
      expect(document.querySelector(selector)).toBe(target);
    });
  });
});
