import {
  PACKAGE_NAME,
  // Primitives
  DEFAULT_AUTOGENERATED_ID_PATTERNS,
  DEFAULT_UNSTABLE_CLASS_PATTERNS,
  isStableId,
  filterClasses,
  getStableId,
  describeRelative,
  explicitTrackingAttribute,
  stableIdStrategy,
  // Orchestration
  runOrchestrator,
  DEFAULT_STRATEGIES,
  fallbackCssPath,
  resolveSelectorConfig,
  DEFAULT_RESOLVED_CONFIG,
  createSelectorEngine,
} from '../src';

describe('@amplitude/element-selector — public API surface', () => {
  it('exports the package name and version', () => {
    expect(PACKAGE_NAME).toBe('@amplitude/element-selector');
  });

  it('exports the default pattern packs', () => {
    expect(DEFAULT_AUTOGENERATED_ID_PATTERNS.length).toBeGreaterThan(0);
    expect(DEFAULT_UNSTABLE_CLASS_PATTERNS.length).toBeGreaterThan(0);
  });

  it('exports primitive helpers', () => {
    expect(typeof isStableId).toBe('function');
    expect(typeof filterClasses).toBe('function');
    expect(typeof getStableId).toBe('function');
    expect(typeof describeRelative).toBe('function');
  });

  it('exports both strategies with stable names', () => {
    expect(explicitTrackingAttribute.name).toBe('explicitTrackingAttribute');
    expect(stableIdStrategy.name).toBe('stableId');
  });

  it('exports the orchestrator and fallback', () => {
    expect(typeof runOrchestrator).toBe('function');
    expect(typeof fallbackCssPath).toBe('function');
    expect(DEFAULT_STRATEGIES.length).toBeGreaterThan(0);
  });

  it('exports the config resolver with a frozen default snapshot', () => {
    expect(typeof resolveSelectorConfig).toBe('function');
    expect(DEFAULT_RESOLVED_CONFIG.enabled).toBe(false);
    expect(DEFAULT_RESOLVED_CONFIG.explicitTrackingAttribute).toBe('data-amp-track-id');
  });

  it('exports the engine factory', () => {
    expect(typeof createSelectorEngine).toBe('function');
  });
});
