/**
 * @jest-environment jsdom
 */
import { runOrchestrator, DEFAULT_STRATEGIES } from '../src/orchestrator';
import { ResolvedSelectorConfig, Strategy } from '../src/types';

const baseConfig: ResolvedSelectorConfig = {
  enabled: true,
  explicitTrackingAttribute: 'data-amp-track-id',
  autogeneratedIdPatterns: [/^:r[0-9a-z]+:$/, /\d{4,}/],
  unstableClassPatterns: [],
  maxAncestorWalkDepth: undefined,
  shadowDomEnabled: false,
  maxShadowDomDepth: 1,
};

function setBody(html: string): void {
  document.body.innerHTML = html;
}

describe('runOrchestrator', () => {
  afterEach(() => {
    document.body.innerHTML = '';
  });

  describe('default chain (explicitTrackingAttribute, stableId)', () => {
    it('returns the explicit-tracking selector when the target itself has the attribute', () => {
      setBody(`<button data-amp-track-id="login-btn">x</button>`);
      const target = document.querySelector('button') as Element;
      const result = runOrchestrator(target, baseConfig);
      expect(result).toBe('[data-amp-track-id="login-btn"]');
    });

    it('walks up to an ancestor with an explicit-tracking attribute and descends back', () => {
      setBody(`
        <section data-amp-track-id="signup-section">
          <div>
            <button>click</button>
          </div>
        </section>
      `);
      const target = document.querySelector('button') as Element;
      const result = runOrchestrator(target, baseConfig);
      expect(result).toBe('[data-amp-track-id="signup-section"] > div:nth-of-type(1) > button:nth-of-type(1)');
    });

    it('falls back to stableId when no explicit-tracking attribute is found anywhere on the walk', () => {
      setBody(`
        <section id="hero">
          <button>click</button>
        </section>
      `);
      const target = document.querySelector('button') as Element;
      const result = runOrchestrator(target, baseConfig);
      expect(result).toBe('section#hero > button:nth-of-type(1)');
    });

    it('returns null when no strategy matches anywhere on the walk', () => {
      // No ids, no explicit attributes — chain returns null and lets the
      // engine invoke the fallback walker.
      setBody(`<div><span><button>x</button></span></div>`);
      const target = document.querySelector('button') as Element;
      const result = runOrchestrator(target, baseConfig);
      expect(result).toBeNull();
    });
  });

  describe('two-pass priority — explicit anchor anywhere beats stableId deeper down', () => {
    it('prefers an ancestor explicit anchor over a closer stableId on the target', () => {
      setBody(`
        <section data-amp-track-id="outer">
          <div>
            <button id="cta-btn">click</button>
          </div>
        </section>
      `);
      const target = document.querySelector('button') as Element;
      const result = runOrchestrator(target, baseConfig);
      // Even though `button#cta-btn` would have worked under stableId,
      // the explicit anchor on the outer section wins on pass 1.
      expect(result).toBe('[data-amp-track-id="outer"] > div:nth-of-type(1) > button:nth-of-type(1)');
    });
  });

  describe('autogenerated-id filtering', () => {
    it('skips a React-style autogen id on the target and walks up to a stable id', () => {
      setBody(`
        <section id="hero">
          <button id=":r5:">click</button>
        </section>
      `);
      const target = document.querySelector('button') as Element;
      const result = runOrchestrator(target, baseConfig);
      // The button's id is filtered, so the orchestrator walks to <section id="hero">.
      expect(result).toBe('section#hero > button:nth-of-type(1)');
    });

    it('skips a 4-digit-suffixed id (heuristic match)', () => {
      setBody(`
        <section id="hero">
          <button id="row-1234">click</button>
        </section>
      `);
      const target = document.querySelector('button') as Element;
      const result = runOrchestrator(target, baseConfig);
      expect(result).toBe('section#hero > button:nth-of-type(1)');
    });
  });

  describe('uniqueness — fall through when the candidate matches multiple elements', () => {
    it('returns null if the only anchor candidate is ambiguous in scope', () => {
      // Two elements with the same id is invalid HTML but happens in the wild.
      // The orchestrator's uniqueness check guards against emitting a selector
      // that the dashboard / extension would later resolve to the wrong node.
      setBody(`
        <section>
          <div id="dupe"><button>a</button></div>
          <div id="dupe"><button>b</button></div>
        </section>
      `);
      const target = document.querySelectorAll('button')[1] as Element;
      const result = runOrchestrator(target, baseConfig);
      // `div#dupe > button:nth-of-type(1)` would resolve to TWO elements, so
      // the orchestrator rejects it and (since no other anchor is available)
      // falls through to null.
      expect(result).toBeNull();
    });
  });

  describe('maxAncestorWalkDepth', () => {
    it('honors the depth limit', () => {
      setBody(`
        <section id="hero">
          <div>
            <div>
              <button>click</button>
            </div>
          </div>
        </section>
      `);
      const target = document.querySelector('button') as Element;
      // Depth limit of 2 means walk stops after target + 2 ancestors → can't
      // reach <section id="hero">, so the chain returns null.
      const limitedConfig: ResolvedSelectorConfig = { ...baseConfig, maxAncestorWalkDepth: 2 };
      const result = runOrchestrator(target, limitedConfig);
      expect(result).toBeNull();
    });

    it('with no depth limit, walks all the way to the document root', () => {
      setBody(`
        <section id="hero">
          <div>
            <div>
              <button>click</button>
            </div>
          </div>
        </section>
      `);
      const target = document.querySelector('button') as Element;
      const result = runOrchestrator(target, baseConfig);
      expect(result).toBe('section#hero > div:nth-of-type(1) > div:nth-of-type(1) > button:nth-of-type(1)');
    });
  });

  describe('custom strategy chain', () => {
    it('uses the provided strategies in the supplied order', () => {
      const sentinel: Strategy = {
        name: 'sentinel',
        try(el) {
          return el.tagName === 'BUTTON' ? '[role="custom-anchor"]' : null;
        },
      };
      setBody(`<div><button role="custom-anchor">x</button></div>`);
      const target = document.querySelector('button') as Element;
      const result = runOrchestrator(target, baseConfig, { strategies: [sentinel] });
      // Only the sentinel runs — default strategies are not consulted.
      expect(result).toBe('[role="custom-anchor"]');
    });

    it('DEFAULT_STRATEGIES is exported in priority order', () => {
      expect(DEFAULT_STRATEGIES.map((s) => s.name)).toEqual(['explicitTrackingAttribute', 'stableId']);
    });
  });

  describe('malformed strategy output', () => {
    it('rejects a malformed selector and falls through rather than throwing', () => {
      const broken: Strategy = {
        name: 'broken',
        try() {
          // querySelectorAll on this throws SyntaxError in jsdom.
          return '[';
        },
      };
      setBody(`<button>x</button>`);
      const target = document.querySelector('button') as Element;
      const result = runOrchestrator(target, baseConfig, { strategies: [broken] });
      expect(result).toBeNull();
    });
  });
});
