/**
 * @jest-environment jsdom
 */
import { explicitTrackingAttribute } from '../../src/strategies/explicit-tracking-attribute';
import { ResolvedSelectorConfig, StrategyContext } from '../../src/types';

const baseConfig: ResolvedSelectorConfig = {
  enabled: true,
  explicitTrackingAttribute: 'data-amp-track-id',
  autogeneratedIdPatterns: [],
  unstableClassPatterns: [],
  maxAncestorWalkDepth: undefined,
};

function ctxFor(scope: ParentNode = document, config: ResolvedSelectorConfig = baseConfig): StrategyContext {
  return { scope, config };
}

function makeElement(attrs: Record<string, string>): Element {
  const el = document.createElement('div');
  Object.entries(attrs).forEach(([key, value]) => {
    el.setAttribute(key, value);
  });
  return el;
}

describe('explicitTrackingAttribute strategy', () => {
  it('has the expected name', () => {
    expect(explicitTrackingAttribute.name).toBe('explicitTrackingAttribute');
  });

  describe('attribute absent', () => {
    it('returns null', () => {
      const el = makeElement({});
      expect(explicitTrackingAttribute.try(el, ctxFor())).toBeNull();
    });
  });

  describe('attribute set with empty value (suppression signal)', () => {
    it('returns null — the strategy does not anchor on suppressed elements', () => {
      const el = makeElement({ 'data-amp-track-id': '' });
      expect(explicitTrackingAttribute.try(el, ctxFor())).toBeNull();
    });
  });

  describe('attribute set with non-empty value', () => {
    it('returns an attribute-selector string wrapping the value in double quotes', () => {
      const el = makeElement({ 'data-amp-track-id': 'login-form' });
      expect(explicitTrackingAttribute.try(el, ctxFor())).toBe('[data-amp-track-id="login-form"]');
    });

    it('escapes embedded double-quotes in the value via JSON encoding', () => {
      const el = makeElement({ 'data-amp-track-id': 'a"b' });
      // JSON.stringify('a"b') → '"a\\"b"' (escapes the inner quote)
      expect(explicitTrackingAttribute.try(el, ctxFor())).toBe('[data-amp-track-id="a\\"b"]');
    });

    it('escapes embedded backslashes in the value via JSON encoding', () => {
      const el = makeElement({ 'data-amp-track-id': 'a\\b' });
      // JSON.stringify('a\\b') → '"a\\\\b"'
      expect(explicitTrackingAttribute.try(el, ctxFor())).toBe('[data-amp-track-id="a\\\\b"]');
    });

    it('produces a selector that resolves to the original element under querySelectorAll', () => {
      const el = makeElement({ 'data-amp-track-id': 'login-form' });
      document.body.appendChild(el);
      const selector = explicitTrackingAttribute.try(el, ctxFor()) as string;
      expect(document.querySelectorAll(selector)[0]).toBe(el);
      el.remove();
    });
  });

  describe('with a customer-configured attribute name', () => {
    const customCfg: ResolvedSelectorConfig = {
      ...baseConfig,
      explicitTrackingAttribute: 'data-track',
    };

    it('reads the configured attribute name and emits a selector targeting it', () => {
      const el = makeElement({ 'data-track': 'cta-primary' });
      expect(explicitTrackingAttribute.try(el, ctxFor(document, customCfg))).toBe('[data-track="cta-primary"]');
    });

    it('ignores the default attribute name when a different one is configured', () => {
      const el = makeElement({ 'data-amp-track-id': 'login-form' });
      expect(explicitTrackingAttribute.try(el, ctxFor(document, customCfg))).toBeNull();
    });
  });
});
