/**
 * @jest-environment jsdom
 */
import { stableId } from '../../src/strategies/stable-id';
import { ResolvedSelectorConfig, StrategyContext } from '../../src/types';

const baseConfig: ResolvedSelectorConfig = {
  enabled: true,
  explicitTrackingAttribute: 'data-amp-track-id',
  autogeneratedIdPatterns: [/^:r[0-9a-z]+:$/, /\d{4,}/],
  unstableClassPatterns: [],
  maxAncestorWalkDepth: undefined,
  shadowDomEnabled: false,
  maxShadowDomDepth: 1,
};

function ctxFor(scope: ParentNode = document, config: ResolvedSelectorConfig = baseConfig): StrategyContext {
  return { scope, config };
}

function makeElement(tag: string, attrs: Record<string, string>): Element {
  const el = document.createElement(tag);
  Object.entries(attrs).forEach(([key, value]) => {
    el.setAttribute(key, value);
  });
  return el;
}

describe('stableId strategy', () => {
  it('has the expected name', () => {
    expect(stableId.name).toBe('stableId');
  });

  describe('no usable id', () => {
    it('returns null when the element has no id', () => {
      const el = makeElement('button', { class: 'cta' });
      expect(stableId.try(el, ctxFor())).toBeNull();
    });

    it('returns null when the id is empty', () => {
      const el = makeElement('button', { id: '' });
      expect(stableId.try(el, ctxFor())).toBeNull();
    });

    it('returns null when the id matches an autogenerated pattern (React useId)', () => {
      const el = makeElement('button', { id: ':r5:' });
      expect(stableId.try(el, ctxFor())).toBeNull();
    });

    it('returns null when the id matches the 4+ digit heuristic', () => {
      const el = makeElement('div', { id: 'product-2134' });
      expect(stableId.try(el, ctxFor())).toBeNull();
    });

    it('returns null when the id is present but suppressed via empty tracking attribute', () => {
      const el = makeElement('div', { id: 'row-A2', 'data-amp-track-id': '' });
      expect(stableId.try(el, ctxFor())).toBeNull();
    });
  });

  describe('stable id present', () => {
    it('returns tag#id for a simple alphanumeric id', () => {
      const el = makeElement('button', { id: 'checkout-button' });
      expect(stableId.try(el, ctxFor())).toBe('button#checkout-button');
    });

    it('returns the tag in lowercase even when the source is uppercase', () => {
      const el = makeElement('SECTION', { id: 'catalog' });
      expect(stableId.try(el, ctxFor())).toBe('section#catalog');
    });

    it('CSS-escapes special characters in the id', () => {
      // CSS.escape adds backslash escapes for characters that aren't valid in identifiers.
      const el = makeElement('div', { id: 'my.id' });
      const result = stableId.try(el, ctxFor()) as string;
      expect(result.startsWith('div#')).toBe(true);
      // The output should round-trip — querySelectorAll should find the element.
      document.body.appendChild(el);
      expect(document.querySelectorAll(result)[0]).toBe(el);
      el.remove();
    });

    it('honors a non-empty tracking attribute by NOT treating it as suppression', () => {
      // The non-empty case is the explicitTrackingAttribute strategy's job; stableId
      // sees a real id with no suppression signal and returns it normally.
      const el = makeElement('main', {
        id: 'dashboard',
        'data-amp-track-id': 'main-dashboard',
      });
      expect(stableId.try(el, ctxFor())).toBe('main#dashboard');
    });

    it('produces a selector that resolves to the original element', () => {
      const el = makeElement('input', { id: 'search-input', type: 'search' });
      document.body.appendChild(el);
      const result = stableId.try(el, ctxFor()) as string;
      expect(document.querySelectorAll(result)[0]).toBe(el);
      el.remove();
    });
  });
});
