name: 'E2E Test'
description: 'Setup environment, build packages, start dev server, and run Playwright E2E tests'

inputs:
  amplitude-api-key:
    description: 'Amplitude API key for E2E tests'
    required: true
  amplitude-user-id:
    description: 'Amplitude user ID for E2E tests'
    required: false
    default: 'github-actions-sdk-user'
  server-port:
    description: 'Port for the dev server'
    required: false
    default: '5173'
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20.x'

runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Install project dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Build all packages
      shell: bash
      run: pnpm build

    - name: Create .env file
      shell: bash
      run: |
        echo "VITE_AMPLITUDE_API_KEY=${{ inputs.amplitude-api-key }}" > .env
        echo "VITE_AMPLITUDE_USER_ID=${{ inputs.amplitude-user-id }}" >> .env

    - name: Start dev server
      shell: bash
      run: |
        pnpm build:vite
        pnpm start --port ${{ inputs.server-port }} &
        sleep 10
        curl -f http://localhost:${{ inputs.server-port }} || exit 1

    - name: Run Playwright tests
      shell: bash
      run: pnpm test:playwright:ci

    - name: Upload Playwright Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results/
        retention-days: 30
