/**
 * @jest-environment jsdom
 */

/**
 * Property-based tests for the engine.
 *
 * The fixed scenarios in `test/scenarios/` lock down behavior for hand-picked
 * cases. These tests run the same engine over a corpus of *randomly generated*
 * DOM trees and assert structural invariants that should hold for every input:
 *
 *   1. `engine.generate(el)` always returns a non-empty string
 *   2. The returned selector, evaluated via `document.querySelector`, resolves
 *      back to exactly the element we passed in
 *   3. Even when the tree is laced with autogenerated ids and unstable
 *      classes, the engine still finds a selector that round-trips
 *
 * We use a hand-rolled seedable PRNG so failures are reproducible without
 * pulling in `fast-check` as a dependency. When a property fails, the seed
 * that triggered it is printed alongside the failure.
 */

import { createSelectorEngine } from '../../src/engine';
import { resolveSelectorConfig } from '../../src/config/resolve-config';

// ===== Deterministic PRNG (Mulberry32) =====
// Lightweight, statistically OK for test generation. Seeded from a constant
// so CI is reproducible; failures log the seed for local replay.
function makeRng(seed: number): () => number {
  let state = seed >>> 0;
  return function next(): number {
    state = (state + 0x6d2b79f5) >>> 0;
    let t = state;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function pick<T>(rng: () => number, items: ReadonlyArray<T>): T {
  return items[Math.floor(rng() * items.length)];
}

function intBetween(rng: () => number, low: number, high: number): number {
  return Math.floor(rng() * (high - low + 1)) + low;
}

// ===== DOM generator =====
const TAGS = [
  'div',
  'span',
  'section',
  'article',
  'main',
  'header',
  'footer',
  'nav',
  'ul',
  'li',
  'p',
  'a',
  'button',
] as const;

// Mix of stable and intentionally autogenerated ids so the engine has to
// exercise the autogen filter on a meaningful fraction of nodes.
const STABLE_IDS = [
  'hero',
  'masthead',
  'menu',
  'container',
  'app',
  'sidebar',
  'main-content',
  'footer-cta',
  'header-nav',
];
const AUTOGEN_IDS = [':r5:', ':r10:', 'radix-A1B2', 'mui-12345', 'session-1700000000', 'row-9999'];

// Mix of stable and unstable classes the fallback must handle.
const STABLE_CLASSES = ['primary', 'callout', 'card', 'avatar', 'logo', 'navbar'];
const UNSTABLE_CLASSES = [
  'p-4',
  'bg-blue-500',
  'hover:underline',
  'css-1abcd23',
  'swiper-slide-active',
  'Mui-selected',
  'is-active',
];

interface GenOptions {
  /** Approximate target tree size. */
  size: number;
  /** Probability (0-1) that any given node gets an id. */
  idProb: number;
  /** Probability (0-1) that an assigned id is autogenerated rather than stable. */
  autogenProb: number;
  /** Probability that any node has 1-3 class names. */
  classProb: number;
}

function genTree(rng: () => number, options: GenOptions): { html: string; targetPath: string } {
  // Pick a unique target id we can use to find the node after rendering.
  const targetMarker = `__target_${Math.floor(rng() * 1_000_000)}`;
  const targetDepth = intBetween(rng, 0, 4);

  function makeNode(depth: number, isOnTargetPath: boolean): string {
    const tag = pick(rng, TAGS);
    const isTarget = isOnTargetPath && depth === targetDepth;

    const attrs: string[] = [];

    // Always tag the target with the marker so we can find it; never give the
    // target itself an id from STABLE/AUTOGEN — we want the engine to anchor
    // on something further up the tree.
    if (isTarget) {
      attrs.push(`data-test-target="${targetMarker}"`);
    } else if (rng() < options.idProb) {
      const id = rng() < options.autogenProb ? pick(rng, AUTOGEN_IDS) : pick(rng, STABLE_IDS);
      attrs.push(`id="${id}"`);
    }

    if (rng() < options.classProb) {
      const n = intBetween(rng, 1, 3);
      const classes: string[] = [];
      for (let i = 0; i < n; i++) {
        classes.push(rng() < 0.5 ? pick(rng, UNSTABLE_CLASSES) : pick(rng, STABLE_CLASSES));
      }
      // class attribute escaping is intentionally simple — none of the candidates have quotes
      attrs.push(`class="${classes.join(' ')}"`);
    }

    if (isTarget || depth >= 6) {
      return `<${tag} ${attrs.join(' ')}>x</${tag}>`;
    }

    // Random number of children, with one of them carrying the target path.
    const childCount = intBetween(rng, 1, 3);
    const targetChildIndex = isOnTargetPath ? intBetween(rng, 0, childCount - 1) : -1;
    const children: string[] = [];
    for (let i = 0; i < childCount; i++) {
      children.push(makeNode(depth + 1, i === targetChildIndex));
    }
    return `<${tag} ${attrs.join(' ')}>${children.join('')}</${tag}>`;
  }

  // Reduce the effective `size` knob to a max depth — easier to bound the
  // tree size that way than to count nodes precisely.
  const html = makeNode(0, true);
  return { html, targetPath: `[data-test-target="${targetMarker}"]` };
}

// ===== Properties =====
const ITERATIONS = 100;
const BASE_SEED = 0xc0ffee;

describe('engine property tests', () => {
  let engine: ReturnType<typeof createSelectorEngine>;

  beforeAll(() => {
    engine = createSelectorEngine(resolveSelectorConfig({ enabled: true }));
  });

  afterEach(() => {
    document.body.innerHTML = '';
  });

  it(`generates a unique-resolving selector for ${String(ITERATIONS)} random DOM trees`, () => {
    let failureSeed: number | null = null;
    let failureMessage = '';

    for (let i = 0; i < ITERATIONS; i++) {
      const seed = BASE_SEED + i;
      const rng = makeRng(seed);
      const { html, targetPath } = genTree(rng, {
        size: 8,
        idProb: 0.5,
        autogenProb: 0.5,
        classProb: 0.7,
      });
      document.body.innerHTML = html;
      const target = document.querySelector(targetPath);
      if (!target) {
        failureSeed = seed;
        failureMessage = `seed ${seed.toString(16)}: target marker not found in generated DOM`;
        break;
      }

      const selector = engine.generate(target);

      if (typeof selector !== 'string' || selector.length === 0) {
        failureSeed = seed;
        failureMessage = `seed ${seed.toString(16)}: engine returned empty selector`;
        break;
      }

      let resolved: Element | null;
      try {
        resolved = document.querySelector(selector);
      } catch (e) {
        const message = e instanceof Error ? e.message : String(e);
        failureSeed = seed;
        failureMessage = `seed ${seed.toString(16)}: emitted selector "${selector}" is malformed — ${message}`;
        break;
      }

      if (resolved !== target) {
        failureSeed = seed;
        failureMessage = `seed ${seed.toString(
          16,
        )}: emitted selector "${selector}" resolved to a different element (or null)`;
        break;
      }

      document.body.innerHTML = '';
    }

    if (failureSeed !== null) {
      throw new Error(
        failureMessage + ` — replay this case by setting BASE_SEED = 0x${failureSeed.toString(16)} and ITERATIONS = 1`,
      );
    }
  });

  it('handles trees where every id is autogenerated (forces fallback to root)', () => {
    let failureSeed: number | null = null;
    let failureMessage = '';

    for (let i = 0; i < 30; i++) {
      const seed = BASE_SEED + 1000 + i;
      const rng = makeRng(seed);
      const { html, targetPath } = genTree(rng, {
        size: 8,
        idProb: 0.6,
        autogenProb: 1.0, // every id is autogenerated
        classProb: 0.8,
      });
      document.body.innerHTML = html;
      const target = document.querySelector(targetPath);
      if (!target) continue;

      const selector = engine.generate(target);
      const resolved = document.querySelector(selector);
      if (resolved !== target) {
        failureSeed = seed;
        failureMessage = `seed ${seed.toString(16)}: autogen-only tree — selector "${selector}" did not round-trip`;
        break;
      }

      document.body.innerHTML = '';
    }

    if (failureSeed !== null) {
      throw new Error(failureMessage);
    }
  });

  it('handles trees with zero ids (pure positional fallback)', () => {
    let failureSeed: number | null = null;
    let failureMessage = '';

    for (let i = 0; i < 30; i++) {
      const seed = BASE_SEED + 2000 + i;
      const rng = makeRng(seed);
      const { html, targetPath } = genTree(rng, {
        size: 8,
        idProb: 0.0, // no ids at all
        autogenProb: 0,
        classProb: 0.8,
      });
      document.body.innerHTML = html;
      const target = document.querySelector(targetPath);
      if (!target) continue;

      const selector = engine.generate(target);
      const resolved = document.querySelector(selector);
      if (resolved !== target) {
        failureSeed = seed;
        failureMessage = `seed ${seed.toString(16)}: no-id tree — selector "${selector}" did not round-trip`;
        break;
      }

      document.body.innerHTML = '';
    }

    if (failureSeed !== null) {
      throw new Error(failureMessage);
    }
  });
});
