name: 'Build and Test'
description: 'Install dependencies, build, test, and lint packages'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'

    - name: Install project dependencies
      run: |
        pnpm install --frozen-lockfile
      shell: bash

    - name: Build all packages
      run: |
        pnpm build
      shell: bash

    - name: Test all packages
      run: |
        pnpm test
      shell: bash

    - name: Lint all packages
      run: |
        pnpm lint
      shell: bash

    - name: Configure Git User
      run: |
        git config --global user.name amplitude-sdk-dev
        git config --global user.email 249154226+amplitude-sdk-dev@users.noreply.github.com
      shell: bash

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      if: github.event.inputs.releaseType != 'dry-run'
      with:
        role-to-assume: arn:aws:iam::358203115967:role/github-actions-role
        aws-region: us-west-2

