name: 'Build and Test'
description: 'Install dependencies, build, test, and lint packages'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
  run-tests:
    description: 'Whether to run unit tests'
    required: false
    default: 'true'
  run-lint:
    description: 'Whether to run lint'
    required: false
    default: 'true'
  configure-git:
    description: 'Whether to configure git user for versioning'
    required: false
    default: 'true'
  configure-aws:
    description: 'Whether to configure AWS credentials'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@ff378ebe6b225b0680b81c1ad4498ae0d1d3a5e3 # v6.0.10

    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'

    - name: Install project dependencies
      run: |
        pnpm install --frozen-lockfile
      shell: bash

    - name: Build all packages
      run: |
        pnpm build
      shell: bash

    - name: Test all packages
      if: inputs.run-tests == 'true'
      run: |
        pnpm test
      shell: bash

    - name: Lint all packages
      if: inputs.run-lint == 'true'
      run: |
        pnpm lint
      shell: bash

    - name: Configure Git User
      if: inputs.configure-git == 'true'
      run: |
        git config --global user.name amplitude-sdk-dev
        git config --global user.email 249154226+amplitude-sdk-dev@users.noreply.github.com
      shell: bash

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@99214aa6889fcddfa57764031d71add364327e59 # v6.1.3
      if: inputs.configure-aws == 'true' && github.event.inputs.releaseType != 'dry-run'
      with:
        role-to-assume: arn:aws:iam::358203115967:role/github-actions-role
        aws-region: us-west-2
