source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

# Exclude the ActiveSupport version known to break CocoaPods startup.
gem 'cocoapods', '>= 1.16.2'
gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'
# Ruby 3.4+ removed default gems CocoaPods still needs (kconv lives in nkf).
gem 'nkf'
