#pragma once

#include <ReactCommon/JavaTurboModule.h>
#include <ReactCommon/TurboModule.h>
#include <jsi/jsi.h>

/**
 * Shadows the autogenerated SRMaskViewSpec.h under
 * android/build/generated/source/codegen/jni/ so autolinking registration
 * resolves SRMaskViewComponentDescriptor to our custom class (with adopt())
 * instead of the codegen typedef. See react-native-screens jni/rnscreens.h.
 */
#include <SRMaskViewComponentDescriptor.h>

namespace facebook {
namespace react {

JSI_EXPORT
std::shared_ptr<TurboModule> SRMaskViewSpec_ModuleProvider(
    const std::string& moduleName,
    const JavaTurboModule::InitParams& params);

} // namespace react
} // namespace facebook
