# Template for jira issue creation in order to creates jira tickets for new github issues to help triage
# Notice that the change of this temple might effect jira issue creation for other repositories
name: Jira Issue Creator

on:
  workflow_call:
    inputs:
      label:
        description: 'Label for Repository'
        type: string
        required: true
      subcomponent:
        description: 'The Subcomponent for the Repository'
        type: string
        required: true
    secrets:
      JIRA_BASE_URL:
        description: 'Jira Base Url'
        required: true
      JIRA_USER_EMAIL:
        description: 'Jira User Email'
        required: true
      JIRA_API_TOKEN:
        description: 'Jira Token'
        required: true
      JIRA_PROJECT:
        description: 'Jira Project'
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: Jira
    name: SDK Bot Jira Issue Creation
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Convert Label String
        id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ inputs.label }}

      - name: Truncate Issue Title
        id: truncate
        run: |
          # Calculate max length for title (255 - length of prefix - length of ellipsis - space)
          PREFIX="[SDK - ${{ inputs.label }}] "
          ELLIPSIS="..."
          MAX_TITLE_LENGTH=$((255 - ${#PREFIX} - ${#ELLIPSIS} - 1))
          # Process and truncate title if needed
          TITLE=$(echo "${{ github.event.issue.title }}" | tr '\n' ' ' | sed 's/"/\\"/g')
          if [ ${#TITLE} -gt $MAX_TITLE_LENGTH ]; then
            TITLE="${TITLE:0:$MAX_TITLE_LENGTH}..."
          fi
          echo "truncated_title=$TITLE" >> $GITHUB_OUTPUT

      - name: Create issue
        id: create
        uses: atlassian/gajira-create@master
        with:
          project: ${{ secrets.JIRA_PROJECT }}
          issuetype: Task
          summary: |
            [SDK - ${{ inputs.label }}] ${{ steps.truncate.outputs.truncated_title }}
          description: |
            ${{ github.event.issue.html_url }}
          fields: '{
            "customfield_11416": {"value": "GitHub"},
            "components": [{"name": "SDK"}],
            "customfield_12028": ["${{ inputs.subcomponent }}"],
            "labels": ["${{ steps.string.outputs.lowercase }}"],
            "customfield_11481": {"value": "Governance"},
            "customfield_11200": {"value": "Developer Experience"}
          }' # Source, Component, Subcomponents, Labels, Pillar, Pod

      - name: Log created issue
        run: echo "Issue AMP-${{ steps.create.outputs.issue }} was created"
