# Creates jira tickets for new github issues to help triage
name: Jira Issue Creator

on:
  issues:
    types: [opened]
  workflow_call:
    inputs:
      label:
        type: string
        default: 'TS'
    secrets:
      JIRA_BASE_URL:
        description: 'Jira Base Url'
        required: true
      JIRA_USER_EMAIL:
        description: 'Jira User Email'
        required: true
      JIRA_API_TOKEN:
        description: 'Jira Token'
        required: true
      JIRA_PROJECT:
        description: 'Jira Project'
        required: true

jobs:
  build:
    runs-on: ubuntu-18.04
    environment: Jira
    name: SDK Bot Jira Issue Creation
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Convert Label String
        id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ inputs.label }}

      - name: Create issue
        id: create
        uses: atlassian/gajira-create@master
        with:
          project: ${{ secrets.JIRA_PROJECT }}
          issuetype: Task
          summary: |
            [SDK - ${{ inputs.label }} ] ${{ github.event.issue.title }}
          description: |
            ${{ github.event.issue.html_url }}
          fields: '{
            "customfield_11794": {"value": "Github"},
            "labels": ["${{ steps.string.outputs.lowercase }}"]
          }' # origin, labels

      - name: Log created issue
        run: echo "Issue AMP-${{ steps.create.outputs.issue }} was created"
